//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate;

@interface PKCacheItem : NSObject
{
    NSDate *_insertDate;
    id _item;
}

@property(readonly, nonatomic) id item; // @synthesize item=_item;
- (void).cxx_destruct;
- (_Bool)hasExpired;
- (id)initWithItem:(id)arg1;

@end

