//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/NSObject-Protocol.h>

@class MKPlaceCardHeaderViewController, NSNumber;

@protocol MKPlaceCardHeaderViewControllerDelegate <NSObject>
- (int)mapTypeForPlaceCardHeaderViewController:(MKPlaceCardHeaderViewController *)arg1;
- (void)placeCardheaderHeaderViewControllerDidSelectRidesharingButton:(MKPlaceCardHeaderViewController *)arg1;
- (void)placeCardheaderHeaderViewControllerDidSelectShareLocationButton:(MKPlaceCardHeaderViewController *)arg1;
- (void)placeCardheaderHeaderViewControllerDidSelectRerouteButton:(MKPlaceCardHeaderViewController *)arg1;
- (void)placeCardheaderHeaderViewControllerDidSelectDirectionsButton:(MKPlaceCardHeaderViewController *)arg1 withTransportTypePreference:(NSNumber *)arg2;

@optional
- (double)placeCardHeaderViewControllerTrailingConstantForTitle:(MKPlaceCardHeaderViewController *)arg1;
@end

