//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Home/HFStaticItemProvider.h>

@class HMService, NSString;

@interface HFAssociatedServiceTypeOptionItemProvider : HFStaticItemProvider
{
    HMService *_service;
    NSString *_serviceType;
}

+ (id)_itemForService:(id)arg1 associatedServiceType:(id)arg2;
+ (id)localizedAssociatedServiceTypeStringForServiceType:(id)arg1;
+ (id)_allItemsForService:(id)arg1 serviceType:(id)arg2;
@property(readonly, nonatomic) NSString *serviceType; // @synthesize serviceType=_serviceType;
@property(readonly, nonatomic) HMService *service; // @synthesize service=_service;
- (void).cxx_destruct;
- (id)initWithService:(id)arg1 serviceType:(id)arg2 home:(id)arg3;
- (id)initWithServiceType:(id)arg1 home:(id)arg2;
- (id)initWithHome:(id)arg1;

@end

