//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CATOperation.h"

@class NSPersistentStore;

@interface RMPersistenceStoreChangeProcessingOperation : CATOperation
{
    NSPersistentStore *_store;
    id <RMPersistenceStoreChangeProcessingOperationDelegate> _delegate;
}

@property(nonatomic) __weak id <RMPersistenceStoreChangeProcessingOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSPersistentStore *store; // @synthesize store=_store;
- (void).cxx_destruct;
- (id)_transactionsAfterToken:(id)arg1 store:(id)arg2 context:(id)arg3;
- (id)_changeTypeForChange:(id)arg1;
- (id)_entityGroupForChange:(id)arg1;
- (void)main;
- (_Bool)isAsynchronous;
- (id)initWithStore:(id)arg1;

@end

