//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SafariServices/WBSFluidProgressStateSource-Protocol.h>
#import <SafariServices/_WKDownloadDelegate-Protocol.h>

@class NSString, NSURL, WBSFluidProgressController, WBSFluidProgressState, _WKDownload;
@protocol _SFDownloadControllerDelegate;

@interface _SFDownloadController : NSObject <_WKDownloadDelegate, WBSFluidProgressStateSource>
{
    long long _downloadingFileType;
    _WKDownload *_fileDownload;
    unsigned long long _downloadBackgroundTaskIdentifier;
    NSString *_fileDownloadPath;
    long long _downloadBytesExpected;
    unsigned long long _downloadBytesLoaded;
    NSURL *_fileDownloadSourceURL;
    _Bool _downloadHasFailed;
    WBSFluidProgressState *_fluidProgressState;
    double _timeLastProgressNotificationWasSent;
    id <_SFDownloadControllerDelegate> _delegate;
    WBSFluidProgressController *_fluidProgressController;
}

@property(retain, nonatomic) WBSFluidProgressController *fluidProgressController; // @synthesize fluidProgressController=_fluidProgressController;
@property(nonatomic) long long downloadingFileType; // @synthesize downloadingFileType=_downloadingFileType;
@property(nonatomic) __weak id <_SFDownloadControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)hasFailedURL;
- (double)estimatedProgress;
- (id)expectedOrCurrentURL;
- (id)progressState;
- (void)clearFluidProgressState;
- (_Bool)createFluidProgressState;
- (void)_downloadDidCancel:(id)arg1;
- (void)_download:(id)arg1 didFailWithError:(id)arg2;
- (void)_downloadDidFinish:(id)arg1;
- (id)_download:(id)arg1 decideDestinationWithSuggestedFilename:(id)arg2 allowOverwrite:(_Bool *)arg3;
- (void)_download:(id)arg1 didReceiveData:(unsigned long long)arg2;
- (void)_clearFileDownloadState;
- (void)_endDownloadBackgroundTask;
- (void)_beginDownloadBackgroundTask:(id)arg1;
- (void)_download:(id)arg1 didReceiveResponse:(id)arg2;
- (void)_downloadDidStart:(id)arg1;
- (void)cancel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

