//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Preferences/PSViewController.h>

#import <VideoSubscriberAccountUI/VSAccountInfoViewControllerDelegate-Protocol.h>
#import <VideoSubscriberAccountUI/VSIdentityProviderControllerDelegate-Protocol.h>
#import <VideoSubscriberAccountUI/VSIdentityProviderPickerViewControllerDelegate-Protocol.h>
#import <VideoSubscriberAccountUI/VSRemoteNotifierDelegate-Protocol.h>

@class NSOperationQueue, NSString, UIViewController, VSAccountStore, VSIdentityProviderController, VSRemoteNotifier;

@interface VSSettingsViewController : PSViewController <VSAccountInfoViewControllerDelegate, VSIdentityProviderControllerDelegate, VSIdentityProviderPickerViewControllerDelegate, VSRemoteNotifierDelegate>
{
    _Bool _shouldPresentIdentityProviderViewController;
    VSIdentityProviderController *_identityProviderController;
    VSAccountStore *_accountStore;
    UIViewController *_currentChildViewController;
    NSOperationQueue *_privateQueue;
    VSRemoteNotifier *_remoteNotifier;
}

@property(retain, nonatomic) VSRemoteNotifier *remoteNotifier; // @synthesize remoteNotifier=_remoteNotifier;
@property(retain, nonatomic) NSOperationQueue *privateQueue; // @synthesize privateQueue=_privateQueue;
@property(retain, nonatomic) UIViewController *currentChildViewController; // @synthesize currentChildViewController=_currentChildViewController;
@property(retain, nonatomic) VSAccountStore *accountStore; // @synthesize accountStore=_accountStore;
@property(nonatomic) _Bool shouldPresentIdentityProviderViewController; // @synthesize shouldPresentIdentityProviderViewController=_shouldPresentIdentityProviderViewController;
@property(retain, nonatomic) VSIdentityProviderController *identityProviderController; // @synthesize identityProviderController=_identityProviderController;
- (void).cxx_destruct;
- (id)_account;
- (void)_dismiss;
- (void)_showInitialIdentityProviderViewController:(id)arg1;
- (void)_startIdentityProviderRequest:(id)arg1 identityProvider:(id)arg2 presentViewControllers:(_Bool)arg3;
- (void)_replaceLastViewControllerWithViewController:(id)arg1;
- (void)_removeCurrentChildViewControllerIfNecessary;
- (void)_updateChildViewController:(id)arg1;
- (void)_setupAppropriateChildViewController;
- (void)_presentError:(id)arg1;
- (void)_presentAlertForError:(id)arg1 offeringToDeleteAccount:(_Bool)arg2;
- (void)accountInfoViewController:(id)arg1 didSelectEditAccountForAccount:(id)arg2 identityProvider:(id)arg3;
- (void)accountInfoViewControllerWantsMoreApps:(id)arg1;
- (void)remoteNotifier:(id)arg1 didReceiveRemoteNotificationWithUserInfo:(id)arg2;
- (void)identityProviderPickerViewController:(id)arg1 didPickIdentityProvider:(id)arg2;
- (void)identityProviderController:(id)arg1 replaceViewControllerWithViewController:(id)arg2;
- (void)identityProviderController:(id)arg1 showViewController:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

