//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PDFKit/NSCopying-Protocol.h>

@class NSDictionary, NSString, NSURL, PDFDocumentPrivate, PDFOutline, PDFSelection;

@interface PDFDocument : NSObject <NSCopying>
{
    PDFDocumentPrivate *_private;
}

- (void).cxx_destruct;
- (void)setPageChangeDelegate:(id)arg1;
- (int)documentId;
- (id)pageFromPageDictionary:(struct CGPDFDictionary *)arg1;
- (_Bool)pageSortsAnnotations;
- (struct __CFDictionary *)gcCreateInfoDictionary;
- (struct __DDScanner *)dataDetector;
- (id)annotationsForFieldName:(id)arg1;
- (id)formData;
- (void)scheduledFindOnPage:(id)arg1;
- (void)cleanupFind;
- (_Bool)findOnPage;
- (void)coreFindStrings:(id)arg1;
- (void)coreFindString:(id)arg1;
- (void)normalizeFindOptions:(unsigned long long)arg1;
- (void)enqueueLayoutThreadForPage:(id)arg1 forPDFView:(id)arg2;
- (void)enqueueDataDetectionForPage:(id)arg1 forPDFView:(id)arg2;
- (id)dataDetectorQueue;
- (id)pageLayoutThreadQueue;
- (id)selectionFromPage:(id)arg1 atPoint:(struct CGPoint)arg2 toPage:(id)arg3 atPoint:(struct CGPoint)arg4 type:(int)arg5;
- (void)setShowsAnnotations:(_Bool)arg1;
- (_Bool)showsAnnotations;
- (id)selectionFromPage:(id)arg1 atCharacterIndex:(unsigned long long)arg2 toPage:(id)arg3 atCharacterIndex:(unsigned long long)arg4;
- (id)selectionFromPage:(id)arg1 atPoint:(struct CGPoint)arg2 toPage:(id)arg3 atPoint:(struct CGPoint)arg4;
@property(readonly, nonatomic) PDFSelection *selectionForEntireDocument;
- (void)cancelFindString;
@property(readonly, nonatomic) _Bool isFinding;
- (void)didMatchString:(id)arg1;
- (id)findString:(id)arg1 fromSelection:(id)arg2 withOptions:(unsigned long long)arg3;
- (void)beginFindStrings:(id)arg1 withOptions:(unsigned long long)arg2;
- (void)beginFindString:(id)arg1 withOptions:(unsigned long long)arg2;
- (id)findString:(id)arg1 withOptions:(unsigned long long)arg2;
@property(readonly, nonatomic) Class pageClass;
- (void)exchangePageAtIndex:(unsigned long long)arg1 withPageAtIndex:(unsigned long long)arg2;
- (void)removePageAtIndex:(unsigned long long)arg1;
- (void)insertPage:(id)arg1 atIndex:(unsigned long long)arg2;
- (unsigned long long)indexForPage:(id)arg1;
- (id)rawPageAtIndex:(unsigned long long)arg1;
- (id)pageAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long pageCount;
- (id)outlineItemForSelection:(id)arg1;
@property(retain, nonatomic) PDFOutline *outlineRoot;
- (_Bool)writeToURL:(id)arg1 withOptions:(id)arg2;
- (_Bool)writeToURL:(id)arg1;
- (_Bool)writeToFile:(id)arg1 withOptions:(id)arg2;
- (_Bool)writeToFile:(id)arg1;
- (id)dataRepresentationWithOptions:(id)arg1;
- (id)dataRepresentation;
@property(nonatomic) __weak id delegate;
@property(readonly, nonatomic) NSString *string;
@property(readonly, nonatomic) long long permissionsStatus;
@property(readonly, nonatomic) _Bool allowsCopying;
@property(readonly, nonatomic) _Bool allowsPrinting;
- (id)passwordUsedForUnlocking;
- (_Bool)unlockWithPassword:(id)arg1;
@property(readonly, nonatomic) _Bool isLocked;
@property(readonly, nonatomic) _Bool isEncrypted;
@property(readonly, nonatomic) int minorVersion;
@property(readonly, nonatomic) int majorVersion;
@property(retain, nonatomic) NSDictionary *documentAttributes;
@property(readonly, nonatomic) struct CGPDFDocument *documentRef;
@property(readonly, nonatomic) NSURL *documentURL;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setDocument:(struct CGPDFDocument *)arg1;
- (id)initWithCGPDFDocument:(struct CGPDFDocument *)arg1;
- (id)initWithData:(id)arg1;
- (id)initWithURL:(id)arg1;
- (id)init;
- (struct __CFData *)newXMPFromData:(id)arg1 preserveExistingXMPMetadata:(_Bool)arg2;
- (void)setDocumentCatalogMetadata:(id)arg1 withNSpace:(id)arg2 prefix:(id)arg3 rootPath:(id)arg4;
- (id)documentCatalogMetadataForRootPath:(id)arg1 withKeys:(id)arg2;
- (_Bool)writeToConsumer:(struct CGDataConsumer *)arg1 withOptions:(id)arg2;
- (id)_dataFromXMP:(struct __CFData *)arg1 withRootPath:(id)arg2 keys:(id)arg3;
- (id)_getNearestOutline:(id)arg1 forDestination:(id)arg2;
- (id)_SASLSanitize:(id)arg1;
- (_Bool)_isNonAsciiSpace:(id)arg1;
- (_Bool)_isCommonlyMappedToNothing:(id)arg1;
- (void)_commonInit;

@end

