//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMapTable, NSMutableArray, NSOperationQueue, NSString, NSURL, PDFForm, PDFOutline, PDFSelection;
@protocol PDFDocumentPageChangeDelegate;

@interface PDFDocumentPrivate : NSObject
{
    struct CGPDFDocument *document;
    NSURL *documentURL;
    int documentId;
    NSMutableArray *pages;
    id delegate;
    _Bool respondsToDidUnlock;
    _Bool respondsToDidFindMatch;
    _Bool respondsToDidBeginDocumentFind;
    _Bool respondsToDidEndDocumentFind;
    _Bool respondsToDidBeginPageFind;
    _Bool respondsToDidEndPageFind;
    _Bool respondsToDidMatchString;
    _Bool respondsToPrintJobTitle;
    _Bool respondsToClassForPage;
    _Bool respondsToClassForAnnotation;
    unsigned long long pageCount;
    int majorVersion;
    int minorVersion;
    _Bool isEncrypted;
    _Bool isUnlocked;
    _Bool allowsPrinting;
    _Bool allowsCopying;
    long long permission;
    NSDictionary *attributes;
    NSString *password;
    PDFOutline *outline;
    NSMapTable *pageDictionaryMap;
    NSOperationQueue *pageLayoutThreadQueue;
    NSOperationQueue *dataDetectorQueue;
    _Bool finding;
    int findModel;
    NSArray *findStrings;
    PDFSelection *findInstance;
    unsigned long long findOptions;
    long long findPageIndex;
    long long findCharIndex;
    long long lastFindPageIndex;
    long long lastFindCharIndex;
    NSMutableArray *findResults;
    _Bool sortAnnotations;
    PDFForm *formData;
    _Bool formDataLoaded;
    NSArray *documentCatalogMetadata;
    NSString *xmpNameSpace;
    NSString *xmpPrefix;
    NSString *xmpRootPath;
    id <PDFDocumentPageChangeDelegate> pageChangeDelegate;
    struct __DDScanner *dataDetector;
}

- (void).cxx_destruct;

@end

