//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <DigitalTouchShared/ETGLSketchRendererDelegate-Protocol.h>

@class CADisplayLink, EAGLContext, ETBoxcarFilterPointFIFO, ETGLSketchRenderer, ETPointFIFO, ETQuadCurvePointFIFO, ETSketchMessage, UIColor;

@interface ETGLSketchView : UIView <ETGLSketchRendererDelegate>
{
    CADisplayLink *_displayLink;
    UIColor *_currentStrokeColor;
    double _lastDisplayLinkTime;
    _Bool _renderingOffscreen;
    unsigned long long _currentStrokeIndex;
    unsigned long long _currentPointIndex;
    unsigned long long _numberOfDrawnStrokes;
    double _renderingDelay;
    double _renderingStartTime;
    double _pauseTime;
    _Bool _playing;
    _Bool _paused;
    _Bool _playbackCompleted;
    _Bool _useFastVerticalWisp;
    float _unitSize;
    ETSketchMessage *_messageData;
    double _wispDelay;
    double _timestampForLastDrawnPoint;
    EAGLContext *_context;
    ETGLSketchRenderer *_renderer;
    ETQuadCurvePointFIFO *_interpolatingFIFO;
    ETBoxcarFilterPointFIFO *_smoothingFIFO;
    ETPointFIFO *_pointFIFO;
    ETQuadCurvePointFIFO *_secondaryInterpolatingFIFO;
    ETBoxcarFilterPointFIFO *_secondarySmoothingFIFO;
    ETPointFIFO *_secondaryPointFIFO;
    unsigned long long _vertexOffset;
    double _delayBetweenStrokes;
    vector_32896a2d _vertexBatches;
    vector_761af77e _controlBatches;
    vector_88016b54 _vertexBatchCount;
    vector_88016b54 _secondaryVertexBatchCount;
}

+ (Class)layerClass;
@property(nonatomic) double delayBetweenStrokes; // @synthesize delayBetweenStrokes=_delayBetweenStrokes;
@property(nonatomic) unsigned long long vertexOffset; // @synthesize vertexOffset=_vertexOffset;
@property(nonatomic) vector_88016b54 secondaryVertexBatchCount; // @synthesize secondaryVertexBatchCount=_secondaryVertexBatchCount;
@property(nonatomic) vector_88016b54 vertexBatchCount; // @synthesize vertexBatchCount=_vertexBatchCount;
@property(nonatomic) vector_b97278d5 controlBatches; // @synthesize controlBatches=_controlBatches;
@property(nonatomic) vector_32896a2d vertexBatches; // @synthesize vertexBatches=_vertexBatches;
@property(nonatomic) float unitSize; // @synthesize unitSize=_unitSize;
@property(retain, nonatomic) ETPointFIFO *secondaryPointFIFO; // @synthesize secondaryPointFIFO=_secondaryPointFIFO;
@property(retain, nonatomic) ETBoxcarFilterPointFIFO *secondarySmoothingFIFO; // @synthesize secondarySmoothingFIFO=_secondarySmoothingFIFO;
@property(retain, nonatomic) ETQuadCurvePointFIFO *secondaryInterpolatingFIFO; // @synthesize secondaryInterpolatingFIFO=_secondaryInterpolatingFIFO;
@property(retain, nonatomic) ETPointFIFO *pointFIFO; // @synthesize pointFIFO=_pointFIFO;
@property(retain, nonatomic) ETBoxcarFilterPointFIFO *smoothingFIFO; // @synthesize smoothingFIFO=_smoothingFIFO;
@property(retain, nonatomic) ETQuadCurvePointFIFO *interpolatingFIFO; // @synthesize interpolatingFIFO=_interpolatingFIFO;
@property(retain, nonatomic) ETGLSketchRenderer *renderer; // @synthesize renderer=_renderer;
@property(retain, nonatomic) EAGLContext *context; // @synthesize context=_context;
@property(nonatomic) _Bool useFastVerticalWisp; // @synthesize useFastVerticalWisp=_useFastVerticalWisp;
@property(nonatomic) _Bool playbackCompleted; // @synthesize playbackCompleted=_playbackCompleted;
@property(nonatomic) double timestampForLastDrawnPoint; // @synthesize timestampForLastDrawnPoint=_timestampForLastDrawnPoint;
@property(nonatomic) double wispDelay; // @synthesize wispDelay=_wispDelay;
@property(nonatomic, getter=isPaused) _Bool paused; // @synthesize paused=_paused;
@property(nonatomic, getter=isPlaying) _Bool playing; // @synthesize playing=_playing;
@property(retain, nonatomic) ETSketchMessage *messageData; // @synthesize messageData=_messageData;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)sketchRendererDidReachVertexLimit:(id)arg1;
- (void)clearAllPoints;
- (void)didCompleteStroke;
- (void)handleSketchAtPosition:(struct CGPoint)arg1;
-     // Error parsing type: v44@0:8^16Q24^32B40, name: updateRendererWithSecondaryPoints:count:controlPoint:flush:
-     // Error parsing type: v44@0:8^16Q24^32B40, name: updateRendererWithPoints:count:controlPoint:flush:
- (void)handleTapAtPosition:(struct CGPoint)arg1;
- (void)layoutSubviews;
- (void)clear;
- (void)_endPlayback;
- (struct CGImage *)createImageForTime:(double)arg1;
- (struct CGImage *)createRenderedFrameImage;
- (_Bool)_getCurrentSketchPoint:(CDStruct_e6681aac *)arg1;
- (void)drawView:(id)arg1;
- (_Bool)_doesPoint:(CDStruct_e6681aac *)arg1 predateTime:(double)arg2;
- (void)drawFrameBeforeWisp;
- (void)_drawCurrentPointAdvancingPlayback;
- (void)beginStrokeWithColor:(id)arg1;
- (void)animateOutWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setGLContextAsCurrent;

@end

