//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PRSDirectivesManager : NSObject
{
}

+ (id)sharedDirectivesManager;
- (_Bool)processDirectives:(id)arg1 featureVector:(id)arg2 featureValues:(float *)arg3 maxCount:(unsigned long long)arg4;
- (_Bool)errorWithFeature:(id)arg1 offset:(unsigned long long)arg2 maxOffset:(unsigned long long)arg3;

@end

