//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MobileCoreServices/LSResourceProxy.h>

#import <MobileCoreServices/NSSecureCoding-Protocol.h>

@class NSArray, NSDictionary, NSString, NSURL, NSUUID, _LSLazyPropertyList;

@interface LSBundleProxy : LSResourceProxy <NSSecureCoding>
{
    unsigned long long _bundleFlags;
    unsigned int _plistContentFlags;
    _Bool _foundBackingBundle;
    _Bool _isContainerized;
    _Bool _profileValidated;
    _Bool _UPPValidated;
    NSString *_bundleType;
    NSString *_localizedShortName;
    NSURL *_bundleURL;
    NSString *_bundleExecutable;
    NSString *_bundleVersion;
    NSString *_signerIdentity;
    NSUUID *_cacheGUID;
    unsigned long long _sequenceNumber;
    NSArray *_machOUUIDs;
    _LSLazyPropertyList *__infoDictionary;
    _LSLazyPropertyList *__groupContainers;
    _LSLazyPropertyList *__entitlements;
    _LSLazyPropertyList *__environmentVariables;
}

+ (_Bool)supportsSecureCoding;
+ (id)bundleProxyForCurrentProcess;
+ (id)bundleProxyForURL:(id)arg1;
+ (id)bundleProxyForIdentifier:(id)arg1;
@property(copy, nonatomic, setter=_setEnvironmentVariables:) _LSLazyPropertyList *_environmentVariables; // @synthesize _environmentVariables=__environmentVariables;
@property(copy, nonatomic, setter=_setEntitlements:) _LSLazyPropertyList *_entitlements; // @synthesize _entitlements=__entitlements;
@property(copy, nonatomic, setter=_setGroupContainers:) _LSLazyPropertyList *_groupContainers; // @synthesize _groupContainers=__groupContainers;
@property(copy, nonatomic, setter=_setInfoDictionary:) _LSLazyPropertyList *_infoDictionary; // @synthesize _infoDictionary=__infoDictionary;
@property(copy, nonatomic) NSArray *machOUUIDs; // @synthesize machOUUIDs=_machOUUIDs;
@property(readonly, nonatomic) unsigned long long sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
@property(readonly, nonatomic) NSUUID *cacheGUID; // @synthesize cacheGUID=_cacheGUID;
@property(readonly, nonatomic) _Bool UPPValidated; // @synthesize UPPValidated=_UPPValidated;
@property(readonly, nonatomic) _Bool profileValidated; // @synthesize profileValidated=_profileValidated;
@property(readonly, nonatomic) _Bool isContainerized; // @synthesize isContainerized=_isContainerized;
@property(readonly, nonatomic) _Bool foundBackingBundle; // @synthesize foundBackingBundle=_foundBackingBundle;
@property(readonly, nonatomic) NSString *signerIdentity; // @synthesize signerIdentity=_signerIdentity;
@property(readonly, nonatomic) NSString *bundleVersion; // @synthesize bundleVersion=_bundleVersion;
@property(readonly, nonatomic) NSString *bundleExecutable; // @synthesize bundleExecutable=_bundleExecutable;
@property(readonly, nonatomic) NSURL *bundleURL; // @synthesize bundleURL=_bundleURL;
@property(readonly, nonatomic) NSString *localizedShortName; // @synthesize localizedShortName=_localizedShortName;
@property(readonly, nonatomic) NSString *bundleType; // @synthesize bundleType=_bundleType;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)_valueForEqualityTesting;
- (void)setPropertyListCachingStrategy:(unsigned long long)arg1;
- (id)objectForInfoDictionaryKey:(id)arg1 ofClass:(Class)arg2 valuesOfClass:(Class)arg3;
- (id)objectForInfoDictionaryKey:(id)arg1 ofClass:(Class)arg2;
- (id)objectsForInfoDictionaryKeys:(id)arg1;
- (id)localizedValuesForKeys:(id)arg1 fromTable:(id)arg2;
@property(readonly, nonatomic) NSDictionary *groupContainerURLs;
- (id)_groupContainerURLsFromContainerManager;
- (id)entitlementValueForKey:(id)arg1 ofClass:(Class)arg2 valuesOfClass:(Class)arg3;
- (id)entitlementValueForKey:(id)arg1 ofClass:(Class)arg2;
- (id)entitlementValuesForKeys:(id)arg1;
@property(readonly, nonatomic) NSDictionary *entitlements;
@property(readonly, nonatomic) NSDictionary *environmentVariables;
- (id)_environmentVariablesFromContainerManager;
- (void)setLocalizedShortName:(id)arg1;
@property(readonly, nonatomic) NSURL *appStoreReceiptURL; // @dynamic appStoreReceiptURL;
@property(readonly, nonatomic) NSURL *dataContainerURL;
- (id)_dataContainerURLFromContainerManager;
- (unsigned long long)_containerClassForLSBundleType:(id)arg1;
@property(readonly, nonatomic) NSURL *bundleContainerURL;
@property(readonly, nonatomic) NSURL *containerURL;
@property(readonly, nonatomic) NSString *canonicalExecutablePath;
@property(readonly, nonatomic) NSString *bundleIdentifier;
- (id)uniqueIdentifier;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)_initWithBundleUnit:(unsigned int)arg1 bundleType:(unsigned long long)arg2 bundleID:(id)arg3 localizedName:(id)arg4 bundleContainerURL:(id)arg5 dataContainerURL:(id)arg6 resourcesDirectoryURL:(id)arg7 iconsDictionary:(id)arg8 iconFileNames:(id)arg9 version:(id)arg10;

@end

