//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SearchUI/SearchUILayoutFreeSectionView.h>

#import <SearchUI/FUFlightViewControllerDelegate-Protocol.h>

@class NSString, SFFlightCardSection;

@interface SearchUIFlightCardSectionView : SearchUILayoutFreeSectionView <FUFlightViewControllerDelegate>
{
    unsigned long long _lastSelectedLegIndex;
}

@property unsigned long long lastSelectedLegIndex; // @synthesize lastSelectedLegIndex=_lastSelectedLegIndex;
- (void)flightController:(id)arg1 didSelectLeg:(long long)arg2 ofFlight:(long long)arg3;
- (_Bool)spansFullWidth;
- (id)initWithCardSection:(id)arg1 controller:(id)arg2 style:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain) SFFlightCardSection *section; // @dynamic section;
@property(readonly) Class superclass;

@end

