//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSURL, SFCardSection, SearchUITableViewController;
@protocol SFFeedbackListener;

@interface SearchUICardSectionView : UIView
{
    _Bool _spansFullWidth;
    int _defaultSeparatorStyle;
    SearchUITableViewController *_controller;
    unsigned long long _style;
    NSURL *_url;
    SFCardSection *_section;
    id <SFFeedbackListener> _feedbackDelegate;
}

+ (id)dragSubtitleForCardSection:(id)arg1;
+ (id)dragTitleForCardSection:(id)arg1;
+ (_Bool)supportsRecyclingForCardSection:(id)arg1;
@property(nonatomic) __weak id <SFFeedbackListener> feedbackDelegate; // @synthesize feedbackDelegate=_feedbackDelegate;
@property(readonly) _Bool spansFullWidth; // @synthesize spansFullWidth=_spansFullWidth;
@property(retain, nonatomic) SFCardSection *section; // @synthesize section=_section;
@property(nonatomic) int defaultSeparatorStyle; // @synthesize defaultSeparatorStyle=_defaultSeparatorStyle;
@property(retain) NSURL *url; // @synthesize url=_url;
@property unsigned long long style; // @synthesize style=_style;
@property __weak SearchUITableViewController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (void)updateWithCardSection:(id)arg1;
- (_Bool)shouldDrawBackground;
- (_Bool)isAutoLayoutFree;
- (double)separatorInsetForLeadingImage;
- (id)initWithCardSection:(id)arg1 controller:(id)arg2 style:(unsigned long long)arg3;
- (id)initWithCardSection:(id)arg1 style:(unsigned long long)arg2;
- (id)initWithCardSection:(id)arg1 controller:(id)arg2;

@end

