//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FigCaptureSourceFESCompanionFormat : NSObject
{
    int _formatIndex;
    CDStruct_79c71658 _fesDimensions;
}

@property(readonly) CDStruct_79c71658 fesDimensions;
@property(readonly) int formatIndex;
- (id)description;
- (void)dealloc;
- (id)initWithFESCompanionFormatDictionary:(id)arg1;

@end

