//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SGLRUCache;

@interface SGContactAggregator : NSObject
{
    SGLRUCache *_cachedContacts;
}

+ (id)mergeContact:(id)arg1 withContact:(id)arg2;
+ (id)messageIdentifiersGeneratingContact:(id)arg1;
- (void).cxx_destruct;
- (id)augmentSuggestedContactWithContact:(id)arg1 conversationId:(id)arg2 handle:(id)arg3;
- (void)removeContact:(id)arg1;
- (void)clearContactsWithConversationIdentifier:(id)arg1;
- (void)clear;
- (id)init;

@end

