//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaPlayer/MPModelObject.h>

@class MPModelPodcastAuthor, NSString;

@interface MPModelPodcast : MPModelObject
{
    NSString *_title;
    MPModelPodcastAuthor *_author;
    CDUnknownBlockType _artworkCatalogBlock;
}

+ (id)__MPModelPropertyPodcastArtwork__PROPERTY;
+ (id)__artworkCatalogBlock__KEY;
+ (id)__MPModelRelationshipPodcastAuthor__PROPERTY;
+ (id)__author__KEY;
+ (id)__MPModelPropertyPodcastTitle__PROPERTY;
+ (id)__title__KEY;
+ (id)kindWithEpisodeKind:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType artworkCatalogBlock; // @synthesize artworkCatalogBlock=_artworkCatalogBlock;
@property(retain, nonatomic) MPModelPodcastAuthor *author; // @synthesize author=_author;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)artworkCatalog;
- (id)descriptionWithType:(long long)arg1;

@end

