//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AXUIClient;

@interface AXContainerManager : NSObject
{
    AXUIClient *_containerServerClient;
}

+ (id)sharedManager;
@property(retain, nonatomic) AXUIClient *containerServerClient; // @synthesize containerServerClient=_containerServerClient;
- (void).cxx_destruct;
- (void)deleteFileAtAccessibilityContainerPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)writeData:(id)arg1 toFileAtAccessibilityContainerPath:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)readDataForFileAtAccessibilityContainerPath:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

