//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate.h"

@class NSDictionary, NSMutableDictionary, NSString, UIColor, UIGestureRecognizer, _UIStatusBarAction, _UIStatusBarData, _UIStatusBarDataAggregator, _UIStatusBarRegion, _UIStatusBarStyleAttributes;

@interface _UIStatusBar : UIView <UIGestureRecognizerDelegate>
{
    long long _style;
    UIColor *_foregroundColor;
    long long _mode;
    _UIStatusBarData *_currentData;
    NSMutableDictionary *_items;
    NSMutableDictionary *_displayItemStates;
    UIView *_foregroundView;
    _UIStatusBarRegion *_targetRegion;
    id <_UIStatusBarVisualProvider> _visualProvider;
    NSDictionary *_regions;
    _UIStatusBarDataAggregator *_dataAggregator;
    _UIStatusBarData *_currentAggregatedData;
    _UIStatusBarStyleAttributes *_styleAttributes;
    _UIStatusBarAction *_action;
    UIGestureRecognizer *_actionGestureRecognizer;
}

+ (double)heightForOrientation:(long long)arg1;
+ (void)setDefaultVisualProviderClass:(Class)arg1;
+ (_Bool)forceNewCC;
+ (void)setForceNewCC:(_Bool)arg1;
+ (_Bool)forceSplit;
+ (void)setForceSplit:(_Bool)arg1;
+ (void)initialize;
@property(readonly, nonatomic) UIGestureRecognizer *actionGestureRecognizer; // @synthesize actionGestureRecognizer=_actionGestureRecognizer;
@property(retain, nonatomic) _UIStatusBarAction *action; // @synthesize action=_action;
@property(retain, nonatomic) _UIStatusBarStyleAttributes *styleAttributes; // @synthesize styleAttributes=_styleAttributes;
@property(readonly, nonatomic) _UIStatusBarData *currentAggregatedData; // @synthesize currentAggregatedData=_currentAggregatedData;
@property(retain, nonatomic) _UIStatusBarDataAggregator *dataAggregator; // @synthesize dataAggregator=_dataAggregator;
@property(readonly, nonatomic) NSDictionary *regions; // @synthesize regions=_regions;
@property(retain, nonatomic) id <_UIStatusBarVisualProvider> visualProvider; // @synthesize visualProvider=_visualProvider;
@property(nonatomic) __weak _UIStatusBarRegion *targetRegion; // @synthesize targetRegion=_targetRegion;
@property(retain, nonatomic) UIView *foregroundView; // @synthesize foregroundView=_foregroundView;
@property(retain, nonatomic) NSMutableDictionary *displayItemStates; // @synthesize displayItemStates=_displayItemStates;
@property(retain, nonatomic) NSMutableDictionary *items; // @synthesize items=_items;
@property(readonly, nonatomic) _UIStatusBarData *currentData; // @synthesize currentData=_currentData;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
@property(copy, nonatomic) UIColor *foregroundColor; // @synthesize foregroundColor=_foregroundColor;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (struct CGRect)frameForDisplayItemWithIdentifier:(id)arg1;
- (id)itemsDependingOnKeys:(id)arg1;
- (id)stateForDisplayItemWithIdentifier:(id)arg1;
- (id)regionWithIdentifier:(id)arg1;
- (id)displayItemWithIdentifier:(id)arg1;
- (id)itemWithIdentifier:(id)arg1;
- (struct CGSize)intrinsicContentSize;
@property(readonly, nonatomic) UIView *containerView;
- (struct CGRect)frameForRegionWithIdentifier:(id)arg1;
- (id)actionForRegionWithIdentifier:(id)arg1;
- (void)setAction:(id)arg1 forRegionWithIdentifier:(id)arg2;
- (id)_displayItemForExternalRegionIdentifier:(id)arg1;
- (id)_regionForExternalRegionIdentifier:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)statusBarGesture:(id)arg1;
- (_Bool)_gestureRecognizer:(id)arg1 isInsideRegion:(id)arg2;
- (void)_rearrangeOverflowedItems;
- (void)_updateRegionItems;
- (void)layoutSubviews;
- (void)_performAnimations:(id)arg1;
- (void)updateWithAnimations:(id)arg1;
- (void)_delayUpdatesWithKeys:(id)arg1 fromAnimation:(id)arg2;
- (void)_prepareAnimations:(id)arg1;
- (void)_updateDisplayedItemsWithData:(id)arg1 styleAttributes:(id)arg2 extraAnimations:(id)arg3;
- (void)traitCollectionDidChange:(id)arg1;
- (void)_updateWithAggregatedData:(id)arg1;
- (void)updateWithData:(id)arg1;
- (void)resetVisualProvider;
- (void)_prepareVisualProviderIfNeeded;
@property(readonly, copy) NSString *description;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

