//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <UIKit/UIInterfaceActionConcreteVisualStyleFactory-Protocol.h>

__attribute__((visibility("hidden")))
@interface UIInterfaceActionConcreteVisualStyleFactory_CarPlay : NSObject <UIInterfaceActionConcreteVisualStyleFactory>
{
}

+ (id)styleForTraitCollection:(id)arg1 presentationStyle:(long long)arg2;

@end

