//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LAUtils : NSObject
{
}

+ (id)truncateString:(id)arg1 maxLength:(long long)arg2;
+ (_Bool)isMultiUser;
+ (_Bool)callerRunningOnForeground:(id)arg1;

@end

