//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUbiquitousKeyValueStore;
@protocol DOCTagRegistryDelegate;

@interface DOCTagRegistryICloudDataSource : NSObject
{
    NSUbiquitousKeyValueStore *_store;
    NSObject *_iCloudToken;
    id <DOCTagRegistryDelegate> _delegate;
}

@property(nonatomic) __weak id <DOCTagRegistryDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSObject *iCloudToken; // @synthesize iCloudToken=_iCloudToken;
@property(retain, nonatomic) NSUbiquitousKeyValueStore *store; // @synthesize store=_store;
- (void).cxx_destruct;
- (long long)iCloudTagSerialNumber;
- (long long)iCloudTagVersion;
- (id)iCloudTags;
- (id)iCloudTagsDictionary;
- (void)synchronizeTagsToCloud;
- (void)readTagsFromCloud:(_Bool)arg1;
- (void)kvsStoreDidChange:(id)arg1;
- (void)ubiquityIdentityDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

