//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreServices/SSLookupItem.h>

@interface SSLookupItem (ML3MediaTypeUtil)
- (_Bool)ml_isMovieKind;
- (_Bool)ml_isTVShowKind;
- (_Bool)ml_isVideoKind;
- (_Bool)ml_isAUCVideoKind;
- (_Bool)ml_isAUCAudioKind;
- (_Bool)ml_isAUCItemKind;
- (_Bool)ml_isMusicVideoKind;
- (_Bool)ml_isMusicSongKind;
- (_Bool)ml_isMusicItemKind;
@end

