//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IMCloudKitSyncState, NSArray, NSString;

@interface IMCloudKitSyncProgress : NSObject
{
    IMCloudKitSyncState *_syncState;
    NSString *_progressLabel;
    NSString *_userMessageLabel;
    NSString *_actionLabel;
    long long _actionType;
    double _progressBarValue;
    double _progressBarMax;
}

+ (id)percentString:(double)arg1;
+ (id)percentFormatter;
@property(nonatomic) double progressBarMax; // @synthesize progressBarMax=_progressBarMax;
@property(nonatomic) double progressBarValue; // @synthesize progressBarValue=_progressBarValue;
@property(nonatomic) long long actionType; // @synthesize actionType=_actionType;
@property(retain, nonatomic) NSString *actionLabel; // @synthesize actionLabel=_actionLabel;
@property(retain, nonatomic) NSString *userMessageLabel; // @synthesize userMessageLabel=_userMessageLabel;
@property(retain, nonatomic) NSString *progressLabel; // @synthesize progressLabel=_progressLabel;
@property(readonly, nonatomic) IMCloudKitSyncState *syncState; // @synthesize syncState=_syncState;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool shouldShowUserActionLabel; // @dynamic shouldShowUserActionLabel;
@property(readonly, nonatomic) _Bool shouldShowProgressBar; // @dynamic shouldShowProgressBar;
@property(readonly, nonatomic) NSArray *errors; // @dynamic errors;
@property(readonly, nonatomic) double remainingItems; // @dynamic remainingItems;
@property(readonly, nonatomic) double percentComplete; // @dynamic percentComplete;
- (id)description;
- (void)updateState;
@property(readonly, nonatomic) NSString *percentCompleteString; // @dynamic percentCompleteString;
- (id)initWithSyncState:(id)arg1 syncValue:(double)arg2 maxValue:(double)arg3;
- (id)initWithSyncState:(id)arg1;

@end

