//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Metal/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSString;
@protocol MTLDevice;

@protocol MTLFunction <NSObject>
@property(readonly) NSDictionary *functionConstantsDictionary;
@property(readonly) NSString *name;
@property(readonly) NSArray *stageInputAttributes;
@property(readonly) NSArray *vertexAttributes;
@property(readonly) long long patchControlPointCount;
@property(readonly) unsigned long long patchType;
@property(readonly) unsigned long long functionType;
@property(readonly) id <MTLDevice> device;
@property(copy) NSString *label;
@end

