//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ARGPUWarper : NSObject
{
    id <MTLDevice> _device;
    id <MTLCommandQueue> _commandQueue;
    id <MTLRenderPipelineState> _homographyPipelineState;
}

- (void).cxx_destruct;
-     // Error parsing type: v220@0:8{?={?=[4]}@}16{?={?=[4]}@}112Q208B216, name: warpPlane:toPlane:withLoadAction:synchronous:
-     // Error parsing type: v248@0:8^{__CVBuffer=}16f24{?=[3]}28{?=[4]}76{?={?=[4]}@}140Q236B244, name: warpCameraImage:withExposureOffset:withCameraIntrinsics:withCameraTransform:toPlane:withLoadAction:synchronous:
- (id)init;

@end

