//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HomeUI/HUQuickControlInteractionCoordinatorDelegate-Protocol.h>

@class HFControlItem, HMHome, HUQuickControlInteractionCoordinator, NAValueThrottler, NSString;
@protocol HUQuickControlControllerDelegate;

@interface HUQuickControlController : NSObject <HUQuickControlInteractionCoordinatorDelegate>
{
    _Bool _writesInProgressOrPossible;
    _Bool _hasWrittenAnyNewValues;
    HUQuickControlInteractionCoordinator *_interactionCoordinator;
    HMHome *_home;
    HFControlItem *_controlItem;
    id _modelValue;
    NAValueThrottler *_valueWriteThrottler;
    unsigned long long _inFlightWriteCount;
    id <HUQuickControlControllerDelegate> _delegate;
}

+ (_Bool)matchesControlItem:(id)arg1;
+ (Class)controlItemClass;
@property(nonatomic) __weak id <HUQuickControlControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool hasWrittenAnyNewValues; // @synthesize hasWrittenAnyNewValues=_hasWrittenAnyNewValues;
@property(nonatomic) unsigned long long inFlightWriteCount; // @synthesize inFlightWriteCount=_inFlightWriteCount;
@property(readonly, nonatomic) NAValueThrottler *valueWriteThrottler; // @synthesize valueWriteThrottler=_valueWriteThrottler;
@property(nonatomic, getter=areWritesInProgressOrPossible) _Bool writesInProgressOrPossible; // @synthesize writesInProgressOrPossible=_writesInProgressOrPossible;
@property(readonly, nonatomic) id modelValue; // @synthesize modelValue=_modelValue;
@property(readonly, nonatomic) HFControlItem *controlItem; // @synthesize controlItem=_controlItem;
@property(readonly, nonatomic) HMHome *home; // @synthesize home=_home;
- (void).cxx_destruct;
- (_Bool)hasModelValueChangedForInteractionCoordinator:(id)arg1;
- (void)interactionCoordinator:(id)arg1 interactionStateDidChange:(_Bool)arg2;
- (void)interactionCoordinator:(id)arg1 viewValueDidChange:(id)arg2;
- (void)modelValueDidChange;
@property(readonly, copy, nonatomic) NSString *overrideSecondaryStatusText;
@property(readonly, copy, nonatomic) NSString *overrideStatusText;
@property(readonly, copy, nonatomic) NSString *title;
- (id)controlToViewValueTransformer;
- (id)viewProfile;
- (id)createInteractionCoordinator;
- (void)_updateInteractionState;
- (void)_writeModelControlValue:(id)arg1;
- (void)_updateValueFromControlItem;
- (void)controlItemDidUpdateExternally;
- (void)_setModelValue:(id)arg1 writeValue:(_Bool)arg2;
@property(readonly, nonatomic) HUQuickControlInteractionCoordinator *interactionCoordinator; // @synthesize interactionCoordinator=_interactionCoordinator;
- (id)init;
- (id)initWithControlItem:(id)arg1 home:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

