//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class HUQuickControlPresentationCoordinator, UIViewController;
@protocol HUQuickControlsHost;

@protocol HUQuickControlsHost
- (void)childViewController:(UIViewController<HUQuickControlsHost> *)arg1 didEndQuickControlsPresentation:(HUQuickControlPresentationCoordinator *)arg2;
- (void)childViewController:(UIViewController<HUQuickControlsHost> *)arg1 willBeginQuickControlsPresentation:(HUQuickControlPresentationCoordinator *)arg2;
@end

