//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import <HomeUI/HUCellSeparatorAppearanceDefining-Protocol.h>

@class HUItemTableSectionHeaderFooterView, NSString;

@interface HUSectionHeaderFooterCell : UITableViewCell <HUCellSeparatorAppearanceDefining>
{
    HUItemTableSectionHeaderFooterView *_headerFooterView;
}

@property(readonly, nonatomic) HUItemTableSectionHeaderFooterView *headerFooterView; // @synthesize headerFooterView=_headerFooterView;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool prefersSeparatorsHidden;
- (void)prepareForReuse;
- (struct CGSize)systemLayoutSizeFittingSize:(struct CGSize)arg1 withHorizontalFittingPriority:(float)arg2 verticalFittingPriority:(float)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

