//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NTPBCoverArticlesConfig;

@interface FCCoverArticlesConfiguration : NSObject
{
    NTPBCoverArticlesConfig *_coverArticlesConfig;
    NSString *_feedID;
}

@property(readonly, nonatomic) NSString *feedID; // @synthesize feedID=_feedID;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithPBCoverArticleConfig:(id)arg1;

@end

