//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FCPromise;

@interface FCPendingPromise : NSObject
{
    FCPromise *_promise;
    CDUnknownBlockType _resolve;
    CDUnknownBlockType _reject;
}

@property(copy, nonatomic) CDUnknownBlockType reject; // @synthesize reject=_reject;
@property(copy, nonatomic) CDUnknownBlockType resolve; // @synthesize resolve=_resolve;
@property(retain, nonatomic) FCPromise *promise; // @synthesize promise=_promise;
- (void).cxx_destruct;
- (id)init;

@end

