//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SearchFoundation/SFStartLocalSearchFeedback.h>

#import <CoreParsec/SFProtobufObject-Protocol.h>

@class NSString, PBCodable;

@interface SFStartLocalSearchFeedback (Protobuf) <SFProtobufObject>
+ (Class)protobufClass;
@property(readonly, nonatomic) PBCodable *protobufMessage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

