//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MCDPCContainer, MCDPCItem, MPWeakTimer, NSIndexPath, UIViewController;

@interface _MCDBrowsableContentTableViewPreloader : NSObject
{
    _Bool _cancelled;
    _Bool _isRootTableView;
    _Bool _isTabbedBrowsing;
    UIViewController *_sourceViewController;
    MCDPCContainer *_container;
    MCDPCItem *_item;
    long long _index;
    NSIndexPath *_indexPath;
    CDUnknownBlockType _cancelledBlock;
    MPWeakTimer *_loadingTimer;
}

@property(retain, nonatomic) MPWeakTimer *loadingTimer; // @synthesize loadingTimer=_loadingTimer;
@property(readonly, copy, nonatomic) CDUnknownBlockType cancelledBlock; // @synthesize cancelledBlock=_cancelledBlock;
@property(readonly, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(nonatomic) _Bool isTabbedBrowsing; // @synthesize isTabbedBrowsing=_isTabbedBrowsing;
@property(nonatomic) _Bool isRootTableView; // @synthesize isRootTableView=_isRootTableView;
@property(readonly, nonatomic) long long index; // @synthesize index=_index;
@property(readonly, nonatomic) MCDPCItem *item; // @synthesize item=_item;
@property(readonly, nonatomic) MCDPCContainer *container; // @synthesize container=_container;
@property(readonly, nonatomic) __weak UIViewController *sourceViewController; // @synthesize sourceViewController=_sourceViewController;
@property(nonatomic, getter=isCancelled) _Bool cancelled; // @synthesize cancelled=_cancelled;
- (void).cxx_destruct;
- (void)_displayErrorAlertController:(id)arg1;
- (void)_pushToPlayback:(id)arg1;
- (void)_loadContainerAndPush:(id)arg1;
- (void)loadAndPush;
- (void)_deregister;
- (id)description;
- (void)dealloc;
- (id)initWithContainer:(id)arg1 index:(long long)arg2 sourceViewController:(id)arg3 rootTableView:(_Bool)arg4 tabbedBrowsing:(_Bool)arg5 cancelledBlock:(CDUnknownBlockType)arg6;

@end

