//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;
@protocol OS_dispatch_queue;

@interface HMThreadSafeMutableArrayCollection : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    NSMutableArray *_mutableArray;
}

+ (id)array;
+ (id)arrayWithArray:(id)arg1;
@property(readonly, copy, nonatomic) NSMutableArray *mutableArray; // @synthesize mutableArray=_mutableArray;
@property(readonly, copy, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (_Bool)containsObject:(id)arg1;
- (void)addObjectsFromArray:(id)arg1;
- (void)setIfDifferent:(id)arg1;
- (void)setArray:(id)arg1;
- (id)firstItemWithValue:(id)arg1 forKey:(id)arg2;
- (id)itemsWithValue:(id)arg1 forKey:(id)arg2;
- (id)filteredArrayUsingPredicate:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *array;
@property(readonly, nonatomic) unsigned long long count;
- (void)addObject:(id)arg1;
- (void)removeObjectsInArray:(id)arg1;
- (void)removeObject:(id)arg1;
- (void)replaceObject:(id)arg1;
- (id)initWithArray:(id)arg1;
- (id)firstItemWithCharacteristicType:(id)arg1;
- (id)firstItemWithInstanceID:(id)arg1;
- (id)firstItemWithUniqueIdentifier:(id)arg1;
- (id)firstItemWithUUID:(id)arg1;
- (id)firstItemWithName:(id)arg1;

@end

