//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iWorkImport/TSDDrawableSelection.h>

@class TSCHChartDrawableInfo;

__attribute__((visibility("hidden")))
@interface TNChartSelection : TSDDrawableSelection
{
    TSCHChartDrawableInfo *mChart;
    CDStruct_fc93c73e mReference;
}

+ (Class)archivedSelectionClass;
@property(readonly, nonatomic) TSCHChartDrawableInfo *chart; // @synthesize chart=mChart;
@property(readonly, nonatomic) CDStruct_fc93c73e reference; // @synthesize reference=mReference;
- (void)saveToArchive:(struct ChartSelectionArchive *)arg1 archiver:(id)arg2;
- (id)initFromArchive:(const struct ChartSelectionArchive *)arg1 unarchiver:(id)arg2;
- (_Bool)returnChartFrameForAutoscroll;
- (void)setReference:(CDStruct_fc93c73e)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithChartInfo:(id)arg1;
- (id)initWithChartInfo:(id)arg1 reference:(CDStruct_fc93c73e)arg2;

@end

