//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface TSCH3DChartAddBoundsSceneObjectMode : NSObject
{
}

+ (id)mode;
- (_Bool)hasObjectBoundsForScene:(id)arg1 pipeline:(id)arg2 returningObjectBounds:(struct ObjectBounds *)arg3;
- (id)elementsSceneFromScene:(id)arg1;

@end

