//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iWorkImport/TSSStylePropertyChangeSet.h>

@class TSDSpecReflection, TSDSpecShadow, TSDSpecStroke, TSSSpecDouble;

__attribute__((visibility("hidden")))
@interface TSDMediaStylePropertyChangeSet : TSSStylePropertyChangeSet
{
    TSDSpecStroke *_stroke;
    TSSSpecDouble *_opacity;
    TSDSpecShadow *_shadow;
    TSDSpecReflection *_reflection;
    _Bool _definedStroke;
    _Bool _definedOpacity;
    _Bool _definedShadow;
    _Bool _definedReflection;
}

- (void)enumerateDefinedPropertiesWithBlock:(CDUnknownBlockType)arg1;
- (void)setUnsetSpecForProperty:(int)arg1;
- (void)setSpec:(id)arg1 forProperty:(int)arg2;
- (void)setBoxedValue:(id)arg1 forProperty:(int)arg2;

@end

