//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface TSWPLoadableFontInfo : NSObject
{
    // Error parsing type: AB, name: _attemptedLoad
    NSString *_groupUID;
    NSString *_fontPath;
    NSString *_fontName;
    NSString *_fontFamily;
    struct CGFont *_cgFont;
}

@property(nonatomic) struct CGFont *cgFont; // @synthesize cgFont=_cgFont;
@property(copy, nonatomic) NSString *fontFamily; // @synthesize fontFamily=_fontFamily;
@property(copy, nonatomic) NSString *fontName; // @synthesize fontName=_fontName;
@property(copy, nonatomic) NSString *fontPath; // @synthesize fontPath=_fontPath;
@property(copy, nonatomic) NSString *groupUID; // @synthesize groupUID=_groupUID;
- (void).cxx_destruct;
- (void)releaseCgFont;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)init;
- (void)dealloc;

@end

