//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HealthDaemon/HDProcessStateObserver-Protocol.h>

@class BKSProcessAssertion, CLInUseAssertion, HDClient, HDProfile, NSString;
@protocol OS_dispatch_queue;

@interface HDBackgroundWorkoutRunner : NSObject <HDProcessStateObserver>
{
    HDClient *_client;
    HDProfile *_profile;
    BKSProcessAssertion *_assertion;
    CLInUseAssertion *_coreLocationAssertion;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)_queue_releaseAssertion;
- (_Bool)_queue_takeAssertion;
- (_Bool)_queue_hasBackgroundPermission;
- (void)processDidEnterForeground:(id)arg1;
- (void)stop;
- (void)start;
- (id)initWithClient:(id)arg1 profile:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

