//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HealthDaemon/NSCopying-Protocol.h>

@class HDCloudSyncMasterRecord, NSMutableDictionary, NSSet, NSUUID;

@interface HDCloudSyncFetchOperationResult : NSObject <NSCopying>
{
    long long _status;
    NSMutableDictionary *_storeRecordsCacheMap;
    HDCloudSyncMasterRecord *_masterRecord;
    NSSet *_recordZoneIDs;
    NSUUID *_syncStorePushIdentifier;
    NSSet *_syncStorePullIdentifierSet;
    NSSet *_abandonedStoreIdentifierSet;
    NSSet *_reclaimedIdentifierSet;
}

@property(copy, nonatomic) NSSet *reclaimedIdentifierSet; // @synthesize reclaimedIdentifierSet=_reclaimedIdentifierSet;
@property(copy, nonatomic) NSSet *abandonedStoreIdentifierSet; // @synthesize abandonedStoreIdentifierSet=_abandonedStoreIdentifierSet;
@property(copy, nonatomic) NSSet *syncStorePullIdentifierSet; // @synthesize syncStorePullIdentifierSet=_syncStorePullIdentifierSet;
@property(copy, nonatomic) NSUUID *syncStorePushIdentifier; // @synthesize syncStorePushIdentifier=_syncStorePushIdentifier;
@property(copy, nonatomic) NSSet *recordZoneIDs; // @synthesize recordZoneIDs=_recordZoneIDs;
@property(retain, nonatomic) HDCloudSyncMasterRecord *masterRecord; // @synthesize masterRecord=_masterRecord;
@property(retain, nonatomic) NSMutableDictionary *storeRecordsCacheMap; // @synthesize storeRecordsCacheMap=_storeRecordsCacheMap;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)_storeDescriptionForStoreIdentifer:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithStatus:(long long)arg1;
- (id)initWithStatus:(long long)arg1 storeRecordsCacheMap:(id)arg2 syncStorePushIdentifier:(id)arg3 syncStorePullIdentifiers:(id)arg4 abandonedStoreIdentifiers:(id)arg5 reclaimedIdentifiers:(id)arg6;

@end

