//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HealthDaemon/BBRemoteDataProvider-Protocol.h>
#import <HealthDaemon/HDFitnessFriendsManagerReadyObserver-Protocol.h>

@class BBDataProviderConnection, BBDataProviderProxy, HDFitnessFriendsManager, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface HDFitnessFriendsNotificationBBDataProvider : NSObject <BBRemoteDataProvider, HDFitnessFriendsManagerReadyObserver>
{
    BBDataProviderConnection *_dataProviderConnection;
    BBDataProviderProxy *_dataProviderProxy;
    HDFitnessFriendsManager *_fitnessFriendsManager;
    NSObject<OS_dispatch_queue> *_bulletinQueue;
    NSMutableDictionary *_bulletinByFriendID;
    int notifyGoalCompletionToken;
    int notifyAchievementToken;
    int notifyWorkoutToken;
}

- (void).cxx_destruct;
- (void)handleBulletinActionResponse:(id)arg1;
- (id)bulletinsWithRequestParameters:(id)arg1 lastCleared:(id)arg2;
- (id)clearedInfoForBulletins:(id)arg1 lastClearedInfo:(id)arg2;
- (id)sortDescriptors;
- (void)_migrateSectionInfo;
- (void)dataProviderDidLoad;
- (id)defaultSectionInfo;
- (id)sectionIcon;
- (id)sectionDisplayName;
- (id)universalSectionIdentifier;
- (id)sectionIdentifier;
- (void)_queue_withdrawBulletinRequest:(id)arg1 fromFriendWithID:(id)arg2;
- (void)_queue_addBulletinRequest:(id)arg1 fromContact:(id)arg2 isFakedBulletin:(_Bool)arg3;
- (id)_newPrepopulatedBulletinRequestForContact:(id)arg1;
- (void)_showAchievementEarnedNotificationFromContact:(id)arg1 achievement:(id)arg2 isFakedBulletin:(_Bool)arg3;
- (void)_showWorkoutFinishedNotificationFromContact:(id)arg1 workout:(id)arg2 isFakedBulletin:(_Bool)arg3;
- (void)_showGoalCompletionNotificationFromContact:(id)arg1 activitySnapshot:(id)arg2 isFakedBulletin:(_Bool)arg3;
- (id)_appleWatchSourceRevision;
- (id)_contactWithName:(id)arg1;
- (id)_phoneNumberFromDefaults;
- (id)_fakeSnapshotForDate:(id)arg1;
- (id)_fakeWorkoutDuringDayStartingAtDate:(id)arg1;
- (id)_fakeOutdoorRunningWorkoutDuringDayStartingAtDate:(id)arg1;
- (id)_fakeAchievementDuringDayStartingAtDate:(id)arg1;
- (void)_showFakeWorkoutNotification;
- (void)_showFakeAchievementNotification;
- (void)_showFakeGoalCompletionNotification;
- (void)showAchievementEarnedNotificationFromContact:(id)arg1 achievement:(id)arg2;
- (void)showWorkoutFinishedNotificationFromContact:(id)arg1 workout:(id)arg2;
- (void)showGoalCompletionNotificationFromContact:(id)arg1 activitySnapshot:(id)arg2;
- (void)dealloc;
- (void)fitnessFriendsManagerReady:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

