//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CKContainer, NSHashTable;
@protocol OS_dispatch_queue;

@interface HDFitnessFriendsCloudKitUtility : NSObject
{
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSHashTable *_queue_executingFetchOperations;
    CKContainer *_container;
}

+ (id)shareURLForShare:(id)arg1;
@property(retain, nonatomic) CKContainer *container; // @synthesize container=_container;
- (void).cxx_destruct;
- (void)fetchChangesInSharedDatabaseWithServerChangeTokenCache:(id)arg1 priority:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchChangesInPrivateDatabaseWithServerChangeTokenCache:(id)arg1 priority:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_fetchChangesInDatabase:(id)arg1 serverChangeTokenCache:(id)arg2 priority:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_fetchChangesInZones:(id)arg1 inDatabase:(id)arg2 serverChangeTokenCache:(id)arg3 priority:(long long)arg4 allowRetry:(_Bool)arg5 completion:(CDUnknownBlockType)arg6;
- (void)cancelAllExecutingFetches;
- (void)removeParticpantWithCloudKitAddress:(id)arg1 fromShares:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)addParticipantWithCloudKitAddress:(id)arg1 toShares:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_fetchShareParticipantForEmailAddress:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)acceptSharesWithURLs:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_acceptShareMetadatas:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchShareWithShareRecordID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_fetchShareWithShareRecordID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)createShareAndAssociatedZoneWithShareRecordID:(id)arg1 rootRecord:(id)arg2 otherRecordsToSave:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)saveRecordsIntoPrivateDatabase:(id)arg1 priority:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)forceSaveRecordsIntoPrivateDatabaseIgnoringServerChanges:(id)arg1 priority:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_saveRecordsIntoPrivateDatabaseCreatingZones:(id)arg1 savePolicy:(long long)arg2 priority:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_saveRecordsIntoPrivateDatabase:(id)arg1 savePolicy:(long long)arg2 priority:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_createRecordZonesWithIDs:(id)arg1 priority:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init;
- (id)initWithContainer:(id)arg1;

@end

