//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PGCurationCriteriaFactory : NSObject
{
}

+ (id)_indexSetFromBaseSceneNames:(id)arg1 leafSceneNames:(id)arg2;
+ (id)_tripScenesTrait;
+ (id)_restaurantScenesTrait;
+ (id)_longTripCriteriaWithGraph:(id)arg1;
+ (id)_shortTripCriteriaWithGraph:(id)arg1;
+ (id)_dinnerCriteriaWithGraph:(id)arg1;
+ (id)_lunchCriteriaWithGraph:(id)arg1;
+ (id)_breakfastCriteriaWithGraph:(id)arg1;
+ (id)_nightOutCriteriaWithGraph:(id)arg1;
+ (id)_sportEventCriteriaWithGraph:(id)arg1;
+ (id)_performanceWithGraph:(id)arg1;
+ (id)_entertainmnentWithGraph:(id)arg1;
+ (id)_beachingCriteriaWithGraph:(id)arg1;
+ (id)_winterSportCriteriaWithGraph:(id)arg1;
+ (id)_divingCriteriaWithGraph:(id)arg1;
+ (id)_hikingCriteriaWithGraph:(id)arg1;
+ (id)_holidayEventCriteriaWithGraph:(id)arg1;
+ (id)_anniversaryCriteriaWithCollectionNode:(id)arg1;
+ (id)_birthdayCriteriaWithCollectionNode:(id)arg1;
+ (id)_weddingCriteriaWithGraph:(id)arg1;
+ (id)curationCriteriaWithCollectionNode:(id)arg1 meaningLabel:(id)arg2;

@end

