//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotosGraph/PGGraphIngestProcessor.h>

@interface PGGraphIngestPrefetchEventProcessor : PGGraphIngestProcessor
{
}

- (void)prefetchEventsWithSortedMomentNodes:(id)arg1 locationsToPrefetch:(id *)arg2 progressBlock:(CDUnknownBlockType)arg3;
- (void)runWithGraphUpdate:(id)arg1 progressBlock:(CDUnknownBlockType)arg2;
- (_Bool)shouldRunWithGraphUpdate:(id)arg1;

@end

