//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDateInterval, NSMutableArray, NSString, PGGraphNode;

@interface PGPeopleVisitingSuperset : NSObject
{
    NSMutableArray *_matchedMomentNodes;
    NSString *_locationType;
    unsigned long long _numberOfMomentsWithNoLocation;
    PGGraphNode *_locationNode;
    NSDateInterval *_localDateInterval;
    unsigned long long _numberOfMomentsDuringThisSuperset;
    PGPeopleVisitingSuperset *_parentSuperset;
}

@property(retain) PGPeopleVisitingSuperset *parentSuperset; // @synthesize parentSuperset=_parentSuperset;
@property(readonly) unsigned long long numberOfMomentsDuringThisSuperset; // @synthesize numberOfMomentsDuringThisSuperset=_numberOfMomentsDuringThisSuperset;
@property(readonly) NSArray *matchedMomentNodes; // @synthesize matchedMomentNodes=_matchedMomentNodes;
@property(readonly) NSDateInterval *localDateInterval; // @synthesize localDateInterval=_localDateInterval;
@property(readonly) PGGraphNode *locationNode; // @synthesize locationNode=_locationNode;
- (void).cxx_destruct;
- (id)description;
- (void)reset;
- (void)registerMomentNode:(id)arg1 isInsideSuperset:(_Bool)arg2 hasNoLocation:(_Bool)arg3;
@property(readonly) double insideSupersetUpperRatio;
@property(readonly) double insideSupersetLowerRatio;
- (id)initWithCountryNode:(id)arg1 localDateInterval:(id)arg2;
- (id)initWithStateNode:(id)arg1 localDateInterval:(id)arg2;
- (id)initWithCityNode:(id)arg1 localDateInterval:(id)arg2;
- (id)initWithLocationNode:(id)arg1 localDateInterval:(id)arg2;

@end

