//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImagePickerController.h>

@interface UIImagePickerController (AppleAccountUI)
+ (id)aaui_fixedCropRect:(id)arg1 forOriginalImage:(id)arg2;
@end

