//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCOperation.h>

@class FCAppConfiguration, FCFlintResourceManager, NUEmbedConfigurationOperationResult;

@interface NUEmbedConfigurationOperation : FCOperation
{
    CDUnknownBlockType _completion;
    FCAppConfiguration *_appConfiguration;
    FCFlintResourceManager *_flintResourceManager;
    NUEmbedConfigurationOperationResult *_result;
}

@property(retain, nonatomic) NUEmbedConfigurationOperationResult *result; // @synthesize result=_result;
@property(retain, nonatomic) FCFlintResourceManager *flintResourceManager; // @synthesize flintResourceManager=_flintResourceManager;
@property(retain, nonatomic) FCAppConfiguration *appConfiguration; // @synthesize appConfiguration=_appConfiguration;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;
- (void)operationWillFinishWithError:(id)arg1;
- (void)performOperation;
- (id)initWithAppConfig:(id)arg1 flintResourceManager:(id)arg2;

@end

