//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NUVideoPlaybackAllowabilityManager : NSObject
{
    id <SXVisibilityMonitoring> _visibilityMonitor;
    id <SXVideoPlaybackController> _playbackController;
    id <SXVideoPlaybackPolicy> _playbackPolicy;
}

@property(readonly, nonatomic) id <SXVideoPlaybackPolicy> playbackPolicy; // @synthesize playbackPolicy=_playbackPolicy;
@property(readonly, nonatomic) id <SXVideoPlaybackController> playbackController; // @synthesize playbackController=_playbackController;
@property(readonly, nonatomic) id <SXVisibilityMonitoring> visibilityMonitor; // @synthesize visibilityMonitor=_visibilityMonitor;
- (void).cxx_destruct;
- (id)initWithPlayerVisibilityMonitor:(id)arg1 playbackController:(id)arg2 playbackPolicy:(id)arg3;
- (id)init;

@end

