//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUICore/NSObject-Protocol.h>

@class PXActionPerformer;

@protocol PXActionPerformerDelegate <NSObject>

@optional
- (_Bool)actionPerformer:(PXActionPerformer *)arg1 dismissViewController:(struct NSObject *)arg2 completionHandler:(void (^)(void))arg3;
- (_Bool)actionPerformer:(PXActionPerformer *)arg1 presentViewController:(struct NSObject *)arg2;
- (void)actionPerformer:(PXActionPerformer *)arg1 didChangeState:(unsigned long long)arg2;
@end

