//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotosUICore/PXGadgetProvider.h>

#import "PXCMMInvitationGadgetDelegate.h"
#import "PXCMMWorkflowCoordinatorDelegate.h"
#import "PXChangeObserver.h"
#import "PXSectionedDataSourceManagerObserver.h"

@class NSString, PXCMMInvitationsDataSource, PXCMMInvitationsDataSourceManager, PXCMMWorkflowCoordinator, UIColor;

@interface PXCMMInvitationsGadgetProvider : PXGadgetProvider <PXCMMWorkflowCoordinatorDelegate, PXChangeObserver, PXSectionedDataSourceManagerObserver, PXCMMInvitationGadgetDelegate>
{
    PXCMMInvitationsDataSource *_dataSource;
    _Bool _didGenerateGadgets;
    PXCMMWorkflowCoordinator *_workflowCoordinator;
    id <PXCMMInvitation> _invitationForWorkflow;
    PXCMMInvitationsDataSourceManager *_dataSourceManager;
    UIColor *_backgroundColor;
}

+ (id)new;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, nonatomic) PXCMMInvitationsDataSourceManager *dataSourceManager; // @synthesize dataSourceManager=_dataSourceManager;
- (void).cxx_destruct;
- (void)observable:(id)arg1 didChange:(unsigned long long)arg2 context:(void *)arg3;
- (id)invitationForGadget:(id)arg1;
- (void)workflowCoordinator:(id)arg1 workflowViewController:(id)arg2 didFinishWithActivityState:(unsigned long long)arg3;
- (void)_reportFailureWithTitle:(id)arg1 message:(id)arg2 invitationGadget:(id)arg3;
- (void)_performReviewForInvitationGadget:(id)arg1;
- (void)_performReceiveForInvitationGadget:(id)arg1;
- (id)_workflowCoordinator;
- (void)_performAcceptForInvitationGadget:(id)arg1;
- (void)_setDataSource:(id)arg1 changes:(id)arg2;
- (id)_newGadgetForObjectID:(id)arg1;
- (void)generateGadgets;
- (unsigned long long)estimatedNumberOfGadgets;
- (void)presentInvitationGadget:(id)arg1;
- (id)initWithDataSourceManager:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

