//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUICore/PXObservable.h>

#import <PhotosUICore/PXMutableImageAdjuster-Protocol.h>

@class NSArray, NSString, UIImage;

@interface PXImageAdjuster : PXObservable <PXMutableImageAdjuster>
{
    CDStruct_db2bc502 _needsUpdateFlags;
    _Bool _isUpdatingOutput;
    _Bool _isUpdatedOutputObsolete;
    UIImage *_inputImage;
    UIImage *_outputImage;
    NSArray *_outputFilters;
    struct CGSize _destinationPixelSize;
    struct CGRect _outputContentsRect;
}

@property(copy, nonatomic) NSArray *outputFilters; // @synthesize outputFilters=_outputFilters;
@property(readonly, nonatomic) struct CGRect outputContentsRect; // @synthesize outputContentsRect=_outputContentsRect;
@property(readonly, nonatomic) UIImage *outputImage; // @synthesize outputImage=_outputImage;
@property(readonly, nonatomic) struct CGSize destinationPixelSize; // @synthesize destinationPixelSize=_destinationPixelSize;
@property(readonly, nonatomic) UIImage *inputImage; // @synthesize inputImage=_inputImage;
- (void).cxx_destruct;
- (void)_handleOutputImage:(id)arg1 outputContentsRect:(struct CGRect)arg2;
- (void)_updateOutputIfNeeded;
- (void)_invalidateOutputImage;
- (void)setNeedsUpdate;
@property(readonly, nonatomic) _Bool needsUpdate;
- (void)update;
- (void)_updateIfNeeded;
- (void)setDestinationPixelSize:(struct CGSize)arg1;
- (void)setInputImage:(id)arg1;
- (void)produceOutputImageWithResultHandler:(CDUnknownBlockType)arg1;
- (void)invalidateOutputImage;
- (void)didPerformChanges;
- (id)mutableChangeObject;
- (void)performChanges:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

