//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlaybackCore/NSObject-Protocol.h>

@class MPCPlaybackIntent, MPCPlayer, MPCPlayerItem, MPCPlayerItemContainer;

@protocol MPCPlaybackIntentDataSource <NSObject>
- (void)populateRepresentationsForItem:(MPCPlayerItem *)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)populateContainer:(MPCPlayerItemContainer *)arg1 forPlaybackIntent:(MPCPlaybackIntent *)arg2 completionHandler:(void (^)(NSError *))arg3;
- (void)configureContainer:(MPCPlayerItemContainer *)arg1 forPlaybackIntent:(MPCPlaybackIntent *)arg2 completionHandler:(void (^)(NSError *))arg3;

@optional
- (id)_legacyAlternativeRepresentationForPlaybackIntent:(MPCPlaybackIntent *)arg1 player:(MPCPlayer *)arg2;
@end

