//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MPCPlayer, MPModelPlayEvent, NSOperationQueue;

@interface MPCPlaybackHistoryObserver : NSObject
{
    MPModelPlayEvent *_lastRecordedPlayEvent;
    NSOperationQueue *_operationQueue;
    MPCPlayer *_player;
}

@property(readonly, nonatomic) MPCPlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)_handleChangeFromItem:(id)arg1 toItem:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)initWithPlayer:(id)arg1;
- (id)init;

@end

