//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface BRCTrackingDescriptor : NSObject
{
    _Bool _updateAccessTime;
    CDUnknownBlockType _handler;
}

@property(readonly, nonatomic) _Bool updateAccessTime; // @synthesize updateAccessTime=_updateAccessTime;
@property(readonly, copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
- (void).cxx_destruct;
- (id)initWithHandler:(CDUnknownBlockType)arg1 updateAccessTime:(_Bool)arg2;

@end

