//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FRPersonalizationUtilities : NSObject
{
}

+ (id)diversifyArticles:(id)arg1 withLimit:(unsigned long long)arg2 similarityStartExpectation:(double)arg3 similarityEndExpectation:(double)arg4 publisherDiversificationSlope:(double)arg5 publisherDiversificationYIntercept:(double)arg6;
+ (id)limitArticles:(id)arg1 byHourlyFlowRate:(double)arg2 articleFilterPerPublisher:(double)arg3 timeInterval:(double)arg4;
+ (id)sortArticles:(id)arg1 withArticleToGlobalScoreMap:(id)arg2 readonlyPersonalizationAggregateStore:(id)arg3 configurableValues:(id)arg4 subscribedTagIDs:(id)arg5 mutedTagIDs:(id)arg6 autofavoritedTagIDs:(id)arg7;
+ (id)sortArticles:(id)arg1 withArticleToGlobalScoreMap:(id)arg2 readonlyPersonalizationAggregateStore:(id)arg3 configurableValues:(id)arg4 subscribedTagIDs:(id)arg5 mutedTagIDs:(id)arg6 autofavoritedTagIDs:(id)arg7 sortOptions:(long long)arg8;

@end

