//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCOperation.h"

@class FCCachePolicy, NSArray, NSDate, NSDictionary, NSMutableArray, NTCatchUpOperationForYouRequest, NTCatchUpOperationResults;

@interface NTCatchUpOperation : FCOperation
{
    _Bool _forYouEnabled;
    _Bool _trendingByParsecEnabled;
    id <FCContentContext> _contentContext;
    id <FCFeedPersonalizing> _feedPersonalizer;
    FCCachePolicy *_cachePolicyForArticleLists;
    unsigned long long _maximumCachedAgeForForYou;
    NTCatchUpOperationForYouRequest *_forYouRequest;
    CDUnknownBlockType _sessionProvider;
    unsigned long long _maximumCachedAgeForTrendingByParsec;
    NSDictionary *_resultsByArticleListID;
    NSDictionary *_resultsByArticleIDsRequestID;
    NTCatchUpOperationResults *_forYouResults;
    NTCatchUpOperationResults *_trendingByParsecResults;
    CDUnknownBlockType _catchUpCompletionHandler;
    NSArray *_networkEvents;
    NSDate *_fetchDate;
    NSMutableArray *_articleListRequests;
    NSMutableArray *_articleIDsRequests;
}

@property(retain, nonatomic) NSMutableArray *articleIDsRequests; // @synthesize articleIDsRequests=_articleIDsRequests;
@property(retain, nonatomic) NSMutableArray *articleListRequests; // @synthesize articleListRequests=_articleListRequests;
@property(copy, nonatomic) NSDate *fetchDate; // @synthesize fetchDate=_fetchDate;
@property(copy, nonatomic) NSArray *networkEvents; // @synthesize networkEvents=_networkEvents;
@property(copy, nonatomic) CDUnknownBlockType catchUpCompletionHandler; // @synthesize catchUpCompletionHandler=_catchUpCompletionHandler;
@property(copy, nonatomic) NTCatchUpOperationResults *trendingByParsecResults; // @synthesize trendingByParsecResults=_trendingByParsecResults;
@property(copy, nonatomic) NTCatchUpOperationResults *forYouResults; // @synthesize forYouResults=_forYouResults;
@property(copy, nonatomic) NSDictionary *resultsByArticleIDsRequestID; // @synthesize resultsByArticleIDsRequestID=_resultsByArticleIDsRequestID;
@property(copy, nonatomic) NSDictionary *resultsByArticleListID; // @synthesize resultsByArticleListID=_resultsByArticleListID;
@property(nonatomic, getter=isTrendingByParsecEnabled) _Bool trendingByParsecEnabled; // @synthesize trendingByParsecEnabled=_trendingByParsecEnabled;
@property(nonatomic) unsigned long long maximumCachedAgeForTrendingByParsec; // @synthesize maximumCachedAgeForTrendingByParsec=_maximumCachedAgeForTrendingByParsec;
@property(copy, nonatomic) CDUnknownBlockType sessionProvider; // @synthesize sessionProvider=_sessionProvider;
@property(nonatomic, getter=isForYouEnabled) _Bool forYouEnabled; // @synthesize forYouEnabled=_forYouEnabled;
@property(copy, nonatomic) NTCatchUpOperationForYouRequest *forYouRequest; // @synthesize forYouRequest=_forYouRequest;
@property(nonatomic) unsigned long long maximumCachedAgeForForYou; // @synthesize maximumCachedAgeForForYou=_maximumCachedAgeForForYou;
@property(retain, nonatomic) FCCachePolicy *cachePolicyForArticleLists; // @synthesize cachePolicyForArticleLists=_cachePolicyForArticleLists;
@property(retain, nonatomic) id <FCFeedPersonalizing> feedPersonalizer; // @synthesize feedPersonalizer=_feedPersonalizer;
@property(retain, nonatomic) id <FCContentContext> contentContext; // @synthesize contentContext=_contentContext;
- (void).cxx_destruct;
- (void)_fetchTrendingByParsecResultsIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)_fetchArticleListAndArticleIDsResultsIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)_fetchForYouResultsIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)operationWillFinishWithError:(id)arg1;
- (void)performOperation;
- (void)prepareOperation;
- (_Bool)validateOperation;
- (void)addArticleIDsRequest:(id)arg1;
- (void)addArticleListRequest:(id)arg1;
- (id)init;

@end

