//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CRRecentContactsLibrary;
@protocol CNScheduler;

@interface CNUICoreRecentsManager : NSObject
{
    CRRecentContactsLibrary *_recentsLibrary;
    id <CNScheduler> _workQueue;
}

+ (id)propertyDescriptionAndTransformByRecentKind;
+ (id)supportedRecentsKinds;
+ (id)supportedRecentsDomains;
+ (id)predicateForSearchingPropertiesOfContact:(id)arg1;
+ (id)queryForPropertiesInContact:(id)arg1;
+ (id)descriptorForRequiredKeys;
@property(readonly, nonatomic) id <CNScheduler> workQueue; // @synthesize workQueue=_workQueue;
@property(readonly, nonatomic) CRRecentContactsLibrary *recentsLibrary; // @synthesize recentsLibrary=_recentsLibrary;
- (void).cxx_destruct;
- (void)removeRecents:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)recentsContactsMatchingPropertiesOfContact:(id)arg1;
- (id)initWithRecentsLibrary:(id)arg1 schedulerProvider:(id)arg2;

@end

