//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol NFAssembly <NSObject>
- (void)loadPublicContainer:(id <NFRegistrationContainer>)arg1 privateContainer:(id <NFRegistrationContainer>)arg2;

@optional
- (void)loadedContainer:(id <NFResolver>)arg1;
@end

