//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Silex/SXAdComponent.h>

@interface SXBannerAdComponent : SXAdComponent
{
}

+ (unsigned long long)bannerTypeFromString:(id)arg1;
- (unsigned long long)adType;
- (unsigned long long)bannerTypeWithValue:(id)arg1 withType:(int)arg2;

// Remaining properties
@property(readonly, nonatomic) unsigned long long bannerType; // @dynamic bannerType;

@end

