//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Silex/SXAnalyticsReporting-Protocol.h>

@class NSMutableArray, NSString;
@protocol SXEventCenterDelegate;

@interface SXEventCenter : NSObject <SXAnalyticsReporting>
{
    id <SXEventCenterDelegate> _delegate;
    NSMutableArray *_resignActiveObservers;
    NSMutableArray *_willTerminateObservers;
}

@property(readonly, nonatomic) NSMutableArray *willTerminateObservers; // @synthesize willTerminateObservers=_willTerminateObservers;
@property(readonly, nonatomic) NSMutableArray *resignActiveObservers; // @synthesize resignActiveObservers=_resignActiveObservers;
@property(nonatomic) __weak id <SXEventCenterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)applicationWillTerminate;
- (void)addApplicationWillTerminateObserverBlock:(CDUnknownBlockType)arg1;
- (void)applicationWillResignActive;
- (void)addApplicationWillResignActiveObserverBlock:(CDUnknownBlockType)arg1;
- (void)reportEvent:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

