//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SXVideoControlsViewController;

@protocol SXVideoControlsViewControllerDelegate <NSObject>
- (void)videoControlsViewController:(SXVideoControlsViewController *)arg1 didToggleControlVisibility:(_Bool)arg2;
- (void)videoControlsViewControllsWantsToToggleVolume:(SXVideoControlsViewController *)arg1;
- (void)videoControlsViewControllerWantsSelectCaptions:(SXVideoControlsViewController *)arg1;
- (void)videoControlsViewControllerWantsToLearnMore:(SXVideoControlsViewController *)arg1;
- (void)videoControlsViewControllerWantsToSeePrivacyStatement:(SXVideoControlsViewController *)arg1;
- (void)videoControlsViewControllerWantsToClose:(SXVideoControlsViewController *)arg1;
- (void)videoControlsViewControllerWantsToSeekToStart:(SXVideoControlsViewController *)arg1;
- (_Bool)videoControlsViewControllerWantsToSkipToPreviousVideo:(SXVideoControlsViewController *)arg1;
- (_Bool)videoControlsViewControllerWantsToSkipToNextVideo:(SXVideoControlsViewController *)arg1;
- (void)videoControlsViewControllerWantsToPlay:(SXVideoControlsViewController *)arg1;
- (void)videoControlsViewControllerWantsToPause:(SXVideoControlsViewController *)arg1;
@end

