//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDate;

@interface _TtC12UpNextWidget16SmallSummaryView : UIView
{
    // Error parsing type: , name: allHappenToday
    // Error parsing type: , name: allHappenTomorrow
    // Error parsing type: , name: numberOfEvents
    // Error parsing type: , name: time
    // Error parsing type: , name: label
}

- (CDUnknownBlockType).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, copy) NSDate *time; // @synthesize time;
@property(nonatomic) _Bool allHappenTomorrow; // @synthesize allHappenTomorrow;
@property(nonatomic) _Bool allHappenToday; // @synthesize allHappenToday;
- (double)lastBaselineOffsetFromBottom;
- (double)firstBaselineOffsetFromTop;

@end

