//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PairedUnlock/IDSServiceDelegate-Protocol.h>

@class IDSService, NSMutableDictionary, NSString, PUKeyStore;
@protocol OS_dispatch_queue, PUPeerDelegate;

@interface PUPeer : NSObject <IDSServiceDelegate>
{
    IDSService *_service;
    NSObject<OS_dispatch_queue> *_idsQueue;
    _Bool _unlockEnabled;
    id <PUPeerDelegate> _delegate;
    PUKeyStore *_keyStore;
    NSMutableDictionary *_responseHandlers;
    NSMutableDictionary *_errorHandlers;
    NSObject<OS_dispatch_queue> *_handlerManagementQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *handlerManagementQueue; // @synthesize handlerManagementQueue=_handlerManagementQueue;
@property(retain, nonatomic) NSMutableDictionary *errorHandlers; // @synthesize errorHandlers=_errorHandlers;
@property(retain, nonatomic) NSMutableDictionary *responseHandlers; // @synthesize responseHandlers=_responseHandlers;
@property(retain, nonatomic) PUKeyStore *keyStore; // @synthesize keyStore=_keyStore;
@property(nonatomic, getter=isUnlockEnabled) _Bool unlockEnabled; // @synthesize unlockEnabled=_unlockEnabled;
@property(nonatomic) id <PUPeerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_notifyPairResult:(_Bool)arg1 error:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void)getPasscodeState:(id)arg1;
- (void)didGetPasscodeState:(id)arg1;
- (void)setShouldNotifyNextUnlock:(id)arg1;
- (void)didUnlock:(id)arg1;
- (void)removeLockout:(id)arg1;
- (void)disableOnlyRemoteUnlock:(id)arg1;
- (void)startPasscodeAction:(id)arg1;
- (void)notifyThisDeviceDidUnlock;
- (void)disableOnlyRemoteUnlockWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_notifyStateHasPasscode:(_Bool)arg1 isLocked:(_Bool)arg2 isOnlyRemoteUnlock:(_Bool)arg3 reliably:(_Bool)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (id)_retrieveUnlockOnlyPasscode;
- (void)enableOnlyRemoteUnlockWithPasscode:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)_createAndStoreNewPasscodeWithCurrentPasscode:(id)arg1;
- (void)notifyCurrentState;
- (void)getRemoteDeviceState:(CDUnknownBlockType)arg1;
- (void)unpairForUnlockWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)requestRemoteDeviceRemoveLockout:(CDUnknownBlockType)arg1;
- (void)requestRemoteDeviceDisableOnlyRemoteUnlock;
- (void)requestRemoteDeviceUnlockNotification;
- (void)requestRemoteDevicePasscodeAction:(long long)arg1 type:(long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)pairForUnlockWithPasscode:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)didCompleteRequest:(id)arg1;
- (id)_sendProtobuf:(id)arg1 reliably:(_Bool)arg2 expectsResponse:(_Bool)arg3 responseIdentifier:(id)arg4 error:(id *)arg5;
- (void)_sendResponse:(unsigned short)arg1 toRequestID:(id)arg2 data:(id)arg3 error:(id *)arg4;
- (id)_sendRequest:(unsigned short)arg1 data:(id)arg2 reliably:(_Bool)arg3 expectResponse:(_Bool)arg4 handler:(CDUnknownBlockType)arg5 error:(id *)arg6;
- (void)_sendResultOfMessage:(unsigned short)arg1 requestID:(id)arg2 success:(_Bool)arg3 error:(id)arg4;
- (void)service:(id)arg1 connectedDevicesChanged:(id)arg2;
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5;
- (void)service:(id)arg1 account:(id)arg2 incomingUnhandledProtobuf:(id)arg3 fromID:(id)arg4 context:(id)arg5;
- (void)removeErrorHandlerForRequest:(id)arg1;
- (void)setErrorHandler:(CDUnknownBlockType)arg1 forRequest:(id)arg2;
- (CDUnknownBlockType)errorHandlerForRequest:(id)arg1;
- (void)removeResponseHandlerForRequestMessageID:(id)arg1;
- (void)setResponseHandler:(id)arg1 forRequestMessageID:(id)arg2;
- (id)responseHandlerForRequestMessageID:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

