//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class CLLocation, CLRegion, NSArray, NSDictionary, NSString;

@interface CLSLitePlacemark : NSObject <NSSecureCoding>
{
    struct CLLocationCoordinate2D _coordinate;
    struct CLLocationCoordinate2D _regionCenter;
    double _regionRadius;
    NSString *_regionIdentifier;
    NSDictionary *_addressDictionary;
    NSArray *_areasOfInterest;
}

+ (_Bool)supportsSecureCoding;
+ (id)litePlacemarkFromCLPlacemark:(id)arg1;
@property(readonly, nonatomic) NSArray *areasOfInterest; // @synthesize areasOfInterest=_areasOfInterest;
@property(readonly, nonatomic) NSDictionary *addressDictionary; // @synthesize addressDictionary=_addressDictionary;
- (void).cxx_destruct;
@property(readonly, nonatomic) CLRegion *region;
@property(readonly, nonatomic) CLLocation *location;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

