//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <OpusKit/OKAction.h>

#import "NSSecureCoding.h"
#import "OKActionTapExports.h"

@interface OKActionTap : OKAction <OKActionTapExports, NSSecureCoding>
{
    unsigned long long _tapCount;
}

+ (void)setupJavascriptContext:(id)arg1;
+ (_Bool)supportsSecureCoding;
+ (id)tapActionWithLocation:(struct CGPoint)arg1 tapCount:(unsigned long long)arg2 touchCount:(unsigned long long)arg3 context:(id)arg4;
@property(nonatomic) unsigned long long tapCount; // @synthesize tapCount=_tapCount;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

