//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <iAd/ADCreativeControllerDelegate-Protocol.h>
#import <iAd/ADPrivacyViewControllerInternalDelegate-Protocol.h>
#import <iAd/ADWebViewActionViewControllerDelegate-Protocol.h>

@class ADAdActionPublicAttributes, ADAdImpressionPublicAttributes, ADAdSpaceConfiguration, ADContext, ADCreativeController, ADPrivacyViewController, ADRemoteActionViewController, ADWebViewActionViewController, NSString, NSURL, _UIAsyncInvocation;
@protocol ADAdRecipient;

@interface ADAdSpace : NSObject <ADPrivacyViewControllerInternalDelegate, ADWebViewActionViewControllerDelegate, ADCreativeControllerDelegate>
{
    id <ADAdRecipient> _recipient;
    _Bool _requiresFastVisibiltyTestOnly;
    _Bool _firedAdStatusEvent;
    _Bool _isModalInterstitial;
    _Bool _didInstallCreativeView;
    _Bool _hasImpressed;
    _Bool _visibilityCheckScheduled;
    _Bool _shouldMonitorVisibility;
    _Bool _serviceAdSpaceRequestInProgress;
    _Bool _shouldPresentActionViewControllerWhenReady;
    _Bool _actionViewControllerReadyForPresentation;
    _Bool _actionViewControllerWantsDismissal;
    _Bool _fastVisibilityContextIsFeed;
    _Bool _shouldTearDownCreativeControllerAfterDismissingRemoteActionViewController;
    NSString *_identifier;
    NSURL *_serverURL;
    NSString *_advertisingSection;
    NSString *_authenticationUserName;
    ADContext *_context;
    ADAdImpressionPublicAttributes *_currentAdImpressionPublicAttributes;
    ADAdActionPublicAttributes *_currentActionPublicAttributes;
    long long _visibility;
    double _lastSlowCheck;
    ADCreativeController *_creativeController;
    ADRemoteActionViewController *_remoteActionViewController;
    ADWebViewActionViewController *_webViewActionViewController;
    _UIAsyncInvocation *_remoteViewControllerRequestCancelationInvocation;
    ADPrivacyViewController *_privacyViewController;
    struct CGRect _selectedAdFrame;
}

+ (id)ADIdentifierNameForCreativeType:(int)arg1;
@property(retain, nonatomic) ADPrivacyViewController *privacyViewController; // @synthesize privacyViewController=_privacyViewController;
@property(nonatomic) _Bool shouldTearDownCreativeControllerAfterDismissingRemoteActionViewController; // @synthesize shouldTearDownCreativeControllerAfterDismissingRemoteActionViewController=_shouldTearDownCreativeControllerAfterDismissingRemoteActionViewController;
@property(nonatomic) _Bool fastVisibilityContextIsFeed; // @synthesize fastVisibilityContextIsFeed=_fastVisibilityContextIsFeed;
@property(nonatomic) _Bool actionViewControllerWantsDismissal; // @synthesize actionViewControllerWantsDismissal=_actionViewControllerWantsDismissal;
@property(nonatomic) _Bool actionViewControllerReadyForPresentation; // @synthesize actionViewControllerReadyForPresentation=_actionViewControllerReadyForPresentation;
@property(nonatomic) _Bool shouldPresentActionViewControllerWhenReady; // @synthesize shouldPresentActionViewControllerWhenReady=_shouldPresentActionViewControllerWhenReady;
@property(retain, nonatomic) _UIAsyncInvocation *remoteViewControllerRequestCancelationInvocation; // @synthesize remoteViewControllerRequestCancelationInvocation=_remoteViewControllerRequestCancelationInvocation;
@property(retain, nonatomic) ADWebViewActionViewController *webViewActionViewController; // @synthesize webViewActionViewController=_webViewActionViewController;
@property(retain, nonatomic) ADRemoteActionViewController *remoteActionViewController; // @synthesize remoteActionViewController=_remoteActionViewController;
@property(nonatomic) _Bool serviceAdSpaceRequestInProgress; // @synthesize serviceAdSpaceRequestInProgress=_serviceAdSpaceRequestInProgress;
@property(retain, nonatomic) ADCreativeController *creativeController; // @synthesize creativeController=_creativeController;
@property(nonatomic) double lastSlowCheck; // @synthesize lastSlowCheck=_lastSlowCheck;
@property(nonatomic) _Bool shouldMonitorVisibility; // @synthesize shouldMonitorVisibility=_shouldMonitorVisibility;
@property(nonatomic) _Bool visibilityCheckScheduled; // @synthesize visibilityCheckScheduled=_visibilityCheckScheduled;
@property(nonatomic) long long visibility; // @synthesize visibility=_visibility;
@property(nonatomic) _Bool hasImpressed; // @synthesize hasImpressed=_hasImpressed;
@property(nonatomic) _Bool didInstallCreativeView; // @synthesize didInstallCreativeView=_didInstallCreativeView;
@property(nonatomic) struct CGRect selectedAdFrame; // @synthesize selectedAdFrame=_selectedAdFrame;
@property(nonatomic) _Bool isModalInterstitial; // @synthesize isModalInterstitial=_isModalInterstitial;
@property(nonatomic) _Bool firedAdStatusEvent; // @synthesize firedAdStatusEvent=_firedAdStatusEvent;
@property(retain, nonatomic) ADAdActionPublicAttributes *currentActionPublicAttributes; // @synthesize currentActionPublicAttributes=_currentActionPublicAttributes;
@property(retain, nonatomic) ADAdImpressionPublicAttributes *currentAdImpressionPublicAttributes; // @synthesize currentAdImpressionPublicAttributes=_currentAdImpressionPublicAttributes;
@property(nonatomic) _Bool requiresFastVisibiltyTestOnly; // @synthesize requiresFastVisibiltyTestOnly=_requiresFastVisibiltyTestOnly;
@property(copy, nonatomic) ADContext *context; // @synthesize context=_context;
@property(copy, nonatomic) NSString *authenticationUserName; // @synthesize authenticationUserName=_authenticationUserName;
@property(copy, nonatomic) NSString *advertisingSection; // @synthesize advertisingSection=_advertisingSection;
@property(copy, nonatomic) NSURL *serverURL; // @synthesize serverURL=_serverURL;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)creativeControllerViewDidRequestOpenURL:(id)arg1 withTapLocation:(struct CGPoint)arg2;
- (void)creativeControllerViewDidRequestExpandURL:(id)arg1 withMaximumSize:(struct CGSize)arg2 withTapLocation:(struct CGPoint)arg3;
- (void)creativeControllerViewDidRequestCreateCalendarEvent:(id)arg1 withTapLocation:(struct CGPoint)arg2;
- (void)creativeControllerViewDidRequestCloseWithTapLocation:(struct CGPoint)arg1;
- (void)webViewActionViewControllerHomeButtonWasTapped:(id)arg1;
- (void)safariViewControllerDidFinish:(id)arg1;
- (void)_tearDownWebActionViewController;
- (void)_considerPresentingWebViewActionViewControllerWithURL:(id)arg1;
- (void)_remote_updateActionViewControllerOrientation:(unsigned long long)arg1;
- (void)_remote_requestViewControllerWithClassName:(id)arg1 forAdSpaceControllerWithIdentifier:(id)arg2;
- (void)_remote_resumeBannerMedia;
- (void)_remote_pauseBannerMedia;
- (void)_remote_openURL:(id)arg1;
- (void)_remote_creativeDidFailWithError:(id)arg1;
- (void)impressionPublicAttributesDidLoad:(id)arg1;
- (void)adPrivacyViewControllerDidLinkOut:(id)arg1;
- (void)adPrivacyViewControllerDidRenderTransparency:(id)arg1;
- (void)adPrivacyViewControllerDidAppear:(id)arg1;
- (void)adPrivacyViewController:(id)arg1 didFailWithError:(id)arg2;
- (void)adPrivacyViewControllerDidDismiss:(id)arg1;
- (void)adPrivacyViewControllerDidLoad:(id)arg1;
- (void)showAdTransparency;
- (void)reportNativeClickEvent;
- (void)_notifiyCreativeControllerOfActionViewControllerPresentation;
- (void)_considerPresentingActionViewController;
- (void)_remote_dismissViewControllerWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_remote_dismissViewController;
- (void)_remote_actionViewControllerReadyForPresentation;
- (void)cancelBannerViewAction;
- (void)refuseBannerViewAction;
- (void)_handleMRAIDActionPresentation;
- (void)executeBannerViewActionFrom:(struct CGRect)arg1 withTapLocation:(struct CGPoint)arg2;
- (void)determineActionForTapAtLocation:(struct CGPoint)arg1 inFrame:(struct CGRect)arg2 withMRAIDAction:(id)arg3 completeHandler:(CDUnknownBlockType)arg4;
- (void)stopVisibilityMonitoring;
- (void)startVisibilityMonitoring;
- (void)internalAdTypeDidChange;
- (id)_updateIdentifier;
- (void)updateCreativeControllerVisibility;
- (void)updateVisibility;
- (void)_presentPrivacyViewController;
- (void)uninstallCreativeView;
- (void)installCreativeView;
- (_Bool)canReuseForContext:(id)arg1;
- (void)_clientApplicationDidBecomeActive;
- (void)_clientApplicationDidEnterBackground;
- (void)_remote_close;
- (void)close;
- (void)_tearDownCreativeController;
- (void)_closeConnectionIfNecessary;
@property(readonly, nonatomic) id <ADAdRecipient> recipient;
- (void)_requestAdFromAdSheet;
@property(readonly, nonatomic) ADAdSpaceConfiguration *configuration;
@property(readonly, nonatomic) NSString *connectionAssertionIdentifier;
@property(readonly, copy) NSString *description;
- (id)initForRecipient:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

