//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSURL, NSValue;

@protocol ADWebProcessDelegate <NSObject>

@optional
- (void)webProcessMRAIDJSODidCallOpen:(NSURL *)arg1;
- (void)webProcessMRAIDJSODidCallCreateCalendarEvent:(NSDictionary *)arg1;
- (void)webProcessMRAIDJSODidCallExpand:(NSURL *)arg1 withMaximumSize:(NSValue *)arg2;
- (void)webProcessMRAIDJSODidCallClose;
- (void)webProcessPlugInBrowserContextControllerGlobalObjectIsAvailableForFrame;
- (void)webProcessPlugInWillDestroyBrowserContextController;
- (void)webProcessPlugInDidCreateBrowserContextController;
@end

