//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HMFoundation/HMFMessageTransport.h>

@class HMDDevice, NSMutableArray, NSObject, NSUUID;
@protocol OS_dispatch_queue;

@interface _HMDLegacyWatchSession : HMFMessageTransport
{
    NSUUID *_identifier;
    long long _role;
    HMDDevice *_peer;
    NSObject<OS_dispatch_queue> *_clientQueue;
    NSMutableArray *_pendingTransactions;
}

@property(readonly, nonatomic) NSMutableArray *pendingTransactions; // @synthesize pendingTransactions=_pendingTransactions;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *clientQueue; // @synthesize clientQueue=_clientQueue;
@property(readonly, nonatomic) HMDDevice *peer; // @synthesize peer=_peer;
@property(readonly, nonatomic) long long role; // @synthesize role=_role;
@property(readonly, copy, nonatomic) NSUUID *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)_handleServerReceivedMessage:(id)arg1;
- (id)transactionForIdentifier:(id)arg1;
- (void)_handleClientReceivedMessage:(id)arg1;
- (void)handleReceivedMessage:(id)arg1;
- (void)sendMessage:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)stop;
- (void)dealloc;
- (id)initWithPeer:(id)arg1 role:(long long)arg2 identifier:(id)arg3;
- (id)init;

@end

