//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HomeKitDaemon/HMDEvent.h>

#import <HomeKitDaemon/NSSecureCoding-Protocol.h>

@class HMDCharacteristic, NSNumber, NSUUID;

@interface HMDCharacteristicEvent : HMDEvent <NSSecureCoding>
{
    HMDCharacteristic *_characteristic;
    id _eventValue;
    id _previousValue;
    NSUUID *_accessoryUUID;
    NSNumber *_serviceID;
    NSNumber *_characteristicInstanceID;
}

+ (_Bool)supportsSecureCoding;
+ (id)characteristicEventWithDictionary:(id)arg1 home:(id)arg2 error:(id *)arg3;
@property(readonly, nonatomic) NSNumber *characteristicInstanceID; // @synthesize characteristicInstanceID=_characteristicInstanceID;
@property(readonly, nonatomic) NSNumber *serviceID; // @synthesize serviceID=_serviceID;
@property(readonly, nonatomic) NSUUID *accessoryUUID; // @synthesize accessoryUUID=_accessoryUUID;
@property(retain, nonatomic) id previousValue; // @synthesize previousValue=_previousValue;
@property(retain, nonatomic) id eventValue; // @synthesize eventValue=_eventValue;
@property(readonly, nonatomic) HMDCharacteristic *characteristic; // @synthesize characteristic=_characteristic;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)dumpState;
- (void)replaceCharacteristic:(id)arg1;
- (id)initWithCharacteristic:(id)arg1 eventValue:(id)arg2;

@end

