//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HomeKitDaemon/HMFDumpState-Protocol.h>
#import <HomeKitDaemon/NSSecureCoding-Protocol.h>

@class HAPPairingIdentity, HMDHome, NSMutableArray, NSString, NSUUID;
@protocol OS_dispatch_queue;

@interface HMDUser : NSObject <HMFDumpState, NSSecureCoding>
{
    NSMutableArray *_relayAccessTokens;
    _Bool _remoteAccessAllowed;
    _Bool _remoteGateway;
    unsigned long long _privilege;
    HMDHome *_home;
    NSString *_userID;
    NSString *_relayIdentifier;
    HAPPairingIdentity *_pairingIdentity;
    NSUUID *_uuid;
    NSObject<OS_dispatch_queue> *_propertyQueue;
}

+ (_Bool)supportsSecureCoding;
+ (id)destinationWithUserID:(id)arg1;
+ (id)currentUserWithPrivilege:(unsigned long long)arg1;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *propertyQueue; // @synthesize propertyQueue=_propertyQueue;
@property(copy, nonatomic) NSUUID *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (_Bool)mergeFromUser:(id)arg1 dataVersion:(long long)arg2;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, copy, nonatomic) NSString *encodingRemoteDisplayName;
- (id)initWithCoder:(id)arg1;
- (id)residentCopy;
- (id)userCopy;
- (void)removeRelayAccessTokenForAccessory:(id)arg1;
- (void)removeRelayAccessToken:(id)arg1;
- (void)addRelayAccessToken:(id)arg1;
- (id)relayAccessTokenForAccessory:(id)arg1;
- (_Bool)containsRelayAccessToken:(id)arg1;
- (id)relayAccessTokens;
@property(copy, nonatomic) NSString *relayIdentifier; // @synthesize relayIdentifier=_relayIdentifier;
- (void)configureWithHome:(id)arg1;
- (_Bool)updateAdministrator:(_Bool)arg1;
@property(readonly, getter=isValid) _Bool valid;
@property(readonly, nonatomic) _Bool isOwner;
@property(readonly, nonatomic) _Bool isAdministrator;
@property(nonatomic, getter=isRemoteGateway) _Bool remoteGateway; // @synthesize remoteGateway=_remoteGateway;
- (_Bool)updateRemoteAccessAllowed:(_Bool)arg1;
@property(nonatomic, getter=isRemoteAccessAllowed) _Bool remoteAccessAllowed; // @synthesize remoteAccessAllowed=_remoteAccessAllowed;
@property(readonly, nonatomic, getter=isCurrentUser) _Bool currentUser;
- (id)publicKey;
- (id)pairingUsername;
@property(retain, nonatomic) HAPPairingIdentity *pairingIdentity; // @synthesize pairingIdentity=_pairingIdentity;
@property(readonly, copy, nonatomic) NSString *displayName;
@property(copy, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(nonatomic) __weak HMDHome *home; // @synthesize home=_home;
@property(nonatomic) unsigned long long privilege; // @synthesize privilege=_privilege;
- (unsigned long long)_compatiblePrivilege;
- (id)dumpState;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;
- (id)initWithUserID:(id)arg1 pairingIdentity:(id)arg2 privilege:(unsigned long long)arg3;

// Remaining properties
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

