//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <UserNotificationsUIKit/NCLongLookAnimatorDelegate-Protocol.h>
#import <UserNotificationsUIKit/NCViewControllerTransitioningDelegate-Protocol.h>

@class NCLongLookPresentationController, NCNotificationViewController, NSString;
@protocol NCLongLookAnimator, NCLongLookTransitionDelegateObserver;

@interface NCLongLookTransitionDelegate : NSObject <NCLongLookAnimatorDelegate, NCViewControllerTransitioningDelegate>
{
    NCNotificationViewController *_sourceShortLookVC;
    NCLongLookPresentationController *_longLookPresentationController;
    _Bool _interactive;
    id <NCLongLookTransitionDelegateObserver> _transitioningDelegateObserver;
    long long _transitionInitiator;
}

@property(readonly, nonatomic) long long transitionInitiator; // @synthesize transitionInitiator=_transitionInitiator;
@property(readonly, nonatomic, getter=isInteractive) _Bool interactive; // @synthesize interactive=_interactive;
@property(nonatomic) __weak id <NCLongLookTransitionDelegateObserver> transitioningDelegateObserver; // @synthesize transitioningDelegateObserver=_transitioningDelegateObserver;
- (void).cxx_destruct;
- (void)longLookAnimator:(id)arg1 animationEnded:(_Bool)arg2;
- (void)longLookAnimatorAnimationBegan:(id)arg1;
- (void)transitionAnimator:(id)arg1 didCommitToTransitionWithCoordinator:(id)arg2;
- (id)presentationControllerForPresentedViewController:(id)arg1 presentingViewController:(id)arg2 sourceViewController:(id)arg3;
- (id)interactionControllerForPresentation:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)_longLookPresentationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)_notifyObserverOfTransitionBegin:(_Bool)arg1 withAnimator:(id)arg2 completed:(_Bool)arg3;
@property(readonly, nonatomic) id <NCLongLookAnimator> longLookAnimator;
- (id)initForInteractiveTransition:(_Bool)arg1 withInitiator:(long long)arg2 andSourceShortLookViewController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

