//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UserNotificationsUIKit/NCNotificationRequestContentProvider.h>

@class NSMutableDictionary;

@interface NCNotificationRequestPhoneCoalescingContentProvider : NCNotificationRequestContentProvider
{
    NSMutableDictionary *_topicsDictionary;
}

@property(retain, nonatomic) NSMutableDictionary *topicsDictionary; // @synthesize topicsDictionary=_topicsDictionary;
- (void).cxx_destruct;
- (id)_formattedCountStringForTopic:(id)arg1 count:(unsigned long long)arg2;
- (id)_formattedDecimalStringForNumber:(id)arg1;
- (id)secondaryText;
- (void)_addNotificationRequestToCoalesce:(id)arg1;
- (void)setNotificationRequest:(id)arg1;
- (id)init;
- (id)initWithNotificationRequest:(id)arg1;

@end

