//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardUIServices/BKMatchOperationDelegate-Protocol.h>
#import <SpringBoardUIServices/BKOperationDelegate-Protocol.h>

@class BKDeviceTouchID, NSSet, NSString;
@protocol _SBUIBiometricKitInterfaceDelegate;

@interface _SBUIBiometricKitInterface : NSObject <BKOperationDelegate, BKMatchOperationDelegate>
{
    NSSet *_biometricDevices;
    unsigned long long _enrolledIdentitiesCount;
    int _enrollmentChangedNotifyToken;
    _Bool _isFingerDetected;
    BKDeviceTouchID *_mesaDevice;
    id <_SBUIBiometricKitInterfaceDelegate> _delegate;
}

@property(nonatomic) id <_SBUIBiometricKitInterfaceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_createPresenceDetectOperationsForDeviceTypes:(id)arg1 error:(id *)arg2;
- (void)_sendDelegateEvent:(unsigned long long)arg1;
- (void)matchOperation:(id)arg1 matchedWithResult:(id)arg2;
- (void)operation:(id)arg1 presenceStateChanged:(_Bool)arg2;
- (_Bool)isFingerOn;
- (_Bool)hasEnrolledIdentities;
- (unsigned long long)lockoutState;
- (id)createFingerDetectOperationsWithError:(id *)arg1;
- (id)createPresenceDetectOperationsWithError:(id *)arg1;
- (id)createMatchOperationsWithMode:(unsigned long long)arg1 andCredentialSet:(id)arg2 error:(id *)arg3;
- (_Bool)enableBackgroundFingerDetection:(_Bool)arg1 error:(id *)arg2;
@property(readonly, nonatomic, getter=isTouchIDCapable) _Bool touchIDCapable;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

