//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoardUIServices/SBFLegibilitySettingsProvider-Protocol.h>
#import <SpringBoardUIServices/SBFLegibilitySettingsProviderDelegate-Protocol.h>

@class AVURLAsset, NSDictionary, NSString, NSTimer, SBFWallpaperConfigurationManager, UIImage, _UILegibilitySettings;
@protocol SBFLegibilitySettingsProviderDelegate;

@interface SBSUIWallpaperPreviewViewController : UIViewController <SBFLegibilitySettingsProviderDelegate, SBFLegibilitySettingsProvider>
{
    NSTimer *_dateTimer;
    SBFWallpaperConfigurationManager *_wallpaperConfigurationManager;
    UIImage *_wallpaperImage;
    NSDictionary *_proceduralWallpaper;
    NSDictionary *_proceduralWallpaperOptions;
    _Bool _allowScrolling;
    long long _variant;
    NSString *_name;
    _Bool _colorSamplingEnabled;
    AVURLAsset *_video;
    double _stillTimeInVideo;
    _Bool _motionEnabled;
    id <SBFLegibilitySettingsProviderDelegate> _delegate;
}

@property(nonatomic) _Bool motionEnabled; // @synthesize motionEnabled=_motionEnabled;
@property(nonatomic) __weak id <SBFLegibilitySettingsProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)colorSamplingEnabled;
- (void)setColorSamplingEnabled:(_Bool)arg1;
- (void)statusBarOrientationWillChange:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_startDateTimer;
- (void)_stopDateTimer;
- (void)_updateDateViewAlignmentFromOrientation:(long long)arg1;
- (void)_updateDateView;
- (id)_dateView;
- (id)_wallpaperView;
- (id)_previewView;
- (id)_proceduralWallpaperViewWithFrame:(struct CGRect)arg1 variant:(long long)arg2;
- (id)_wallpaperViewWithFrame:(struct CGRect)arg1 variant:(long long)arg2 options:(id)arg3;
- (id)_wallpaperViewWithFrame:(struct CGRect)arg1 image:(id)arg2 video:(id)arg3 videoURL:(id)arg4 stillTimeInVideo:(double)arg5 supportsCropping:(_Bool)arg6 variant:(long long)arg7;
- (id)_wallpaperViewWithFrame:(struct CGRect)arg1;
- (void)providerLegibilitySettingsChanged:(id)arg1;
@property(readonly, nonatomic) _UILegibilitySettings *legibilitySettings;
- (void)setMotionEnabled:(_Bool)arg1 updateParallaxOnWallpaperView:(_Bool)arg2;
- (void)setWallpaperForLocations:(long long)arg1;
- (double)_parallaxFactor;
@property(readonly) UIImage *wallpaperImage;
- (id)wallpaperConfigurationManager;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithScrollableImage:(id)arg1 video:(id)arg2 time:(double)arg3;
- (id)initWithScrollableImage:(id)arg1;
- (id)initWithImage:(id)arg1 name:(id)arg2 video:(id)arg3 time:(double)arg4;
- (id)initWithImage:(id)arg1 name:(id)arg2;
- (id)initWithProceduralWallpaper:(id)arg1 options:(id)arg2;
- (id)initWithWallpaperVariant:(long long)arg1;
- (id)initWithImage:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

