//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUserDefaults;

@interface SBUIExternalPreferences : NSObject
{
    NSUserDefaults *_soundDefaults;
    _Bool _keyboardPlaysSounds;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool keyboardPlaysSounds; // @synthesize keyboardPlaysSounds=_keyboardPlaysSounds;
- (void).cxx_destruct;
- (id)init;

@end

