//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UNSKeyedObservable;

@interface UNSNotificationCategoryRepository : NSObject
{
    UNSKeyedObservable *_observable;
}

- (void).cxx_destruct;
- (void)performMigrationForBundleIdentifier:(id)arg1;
- (void)performMigration;
- (void)applicationsDidUninstall:(id)arg1;
- (void)setCategories:(id)arg1 forBundleIdentifier:(id)arg2;
- (id)categoriesForBundleIdentifier:(id)arg1;
- (void)removeObserver:(id)arg1 forBundleIdentifier:(id)arg2;
- (void)addObserver:(id)arg1 forBundleIdentifier:(id)arg2;
- (id)initWithObservable:(id)arg1;
- (id)init;

@end

