//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FuseUI/MusicContextualAlertAction.h>

@interface MusicContextualPostAlertAction : MusicContextualAlertAction
{
}

+ (id)_contextualPostActionWithTitle:(id)arg1 socialStoreItem:(id)arg2 presentingViewController:(id)arg3 didDismissHandler:(CDUnknownBlockType)arg4;
+ (id)contextualPostActionsForEntityValueContext:(id)arg1 withAlbumLookUpIfNoParentContainerFound:(_Bool)arg2 presentingViewController:(id)arg3 didDismissHandler:(CDUnknownBlockType)arg4;

@end

