//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class PKFelicaPassProperties, PKPaymentPass, PKPaymentTransaction, PKStackedTextItemGroup, PKStackedTextItemGroupView, UIImageView;

@interface PKFooterTransactionView : UIView
{
    PKStackedTextItemGroup *_displayItem;
    PKStackedTextItemGroupView *_headerView;
    UIView *_separatorView;
    PKStackedTextItemGroupView *_contentView;
    UIImageView *_imageView;
    _Bool _animated;
    PKPaymentPass *_pass;
    PKPaymentTransaction *_transaction;
    PKFelicaPassProperties *_felicaProperties;
}

@property(readonly, nonatomic) PKFelicaPassProperties *felicaProperties; // @synthesize felicaProperties=_felicaProperties;
@property(readonly, nonatomic) PKPaymentTransaction *transaction; // @synthesize transaction=_transaction;
@property(readonly, nonatomic) PKPaymentPass *pass; // @synthesize pass=_pass;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool hasContent;
- (void)setFelicaProperties:(id)arg1 animated:(_Bool)arg2;
- (void)setTransaction:(id)arg1 animated:(_Bool)arg2;
- (void)setPass:(id)arg1 animated:(_Bool)arg2;
- (id)_image;
- (id)_amountText;
- (id)_relativeDateText;
- (id)_statusText;
- (id)_locationText;
- (id)_merchantText;
- (void)_updateContentAnimated:(_Bool)arg1;
- (void)layoutSubviews;
- (void)layoutIfNeededAnimated:(_Bool)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

