//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PassKitUI/MFMailComposeViewControllerDelegate-Protocol.h>

@class NSString, PKPeerPaymentAccount, PKPeerPaymentWebService;
@protocol PKPassLibraryDataProvider, PKPaymentSetupDelegate, PKPaymentSetupViewControllerDelegate, PKPeerPaymentAccountResolutionControllerDelegate;

@interface PKPeerPaymentAccountResolutionController : NSObject <MFMailComposeViewControllerDelegate>
{
    id <PKPeerPaymentAccountResolutionControllerDelegate> _delegate;
    id <PKPassLibraryDataProvider> _passLibraryDataProvider;
    id <PKPaymentSetupViewControllerDelegate> _setupViewControllerDelegate;
    long long _context;
    PKPeerPaymentWebService *_webService;
    PKPeerPaymentAccount *_account;
    id <PKPaymentSetupDelegate> _setupDelegate;
}

@property(nonatomic) __weak id <PKPaymentSetupDelegate> setupDelegate; // @synthesize setupDelegate=_setupDelegate;
@property(retain, nonatomic) PKPeerPaymentAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)_openSupportWebsiteWithWebsiteURL:(id)arg1;
- (void)_callSupportWithPhoneNumber:(id)arg1;
- (void)_emailSupportWithEmailAddress:(id)arg1;
- (void)_peerPaymentAccountChanged:(id)arg1;
- (void)_dismissViewController;
- (void)_presentViewController:(id)arg1;
- (id)_paymentSetupNavigationControllerForProvisioningController:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)_presentContactAppleSupportAlertWithCompletion:(CDUnknownBlockType)arg1;
- (void)_presentIdentityVerificationFlowWithCompletion:(CDUnknownBlockType)arg1;
- (void)_presentActivationFlowWithCompletion:(CDUnknownBlockType)arg1;
- (id)_paymentWebService;
- (_Bool)_canShowContactSupport;
- (id)_peerPaymentPass;
- (_Bool)_hasPeerPaymentPassProvisioned;
- (unsigned long long)currentPeerPaymentAccountResolution;
- (void)presentFlowForAccountResolution:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentResolutionForCurrentAccountStateWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithAccount:(id)arg1 webService:(id)arg2 context:(long long)arg3 delegate:(id)arg4 passLibraryDataProvider:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

