//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ADTargetingData : NSObject
{
    _Bool _updateInFlight;
    NSString *_userTargeting;
    NSString *_toroIDString;
    double _expirationDate;
}

@property _Bool updateInFlight; // @synthesize updateInFlight=_updateInFlight;
@property(nonatomic) double expirationDate; // @synthesize expirationDate=_expirationDate;
@property(retain, nonatomic) NSString *toroIDString; // @synthesize toroIDString=_toroIDString;
@property(retain, nonatomic) NSString *userTargeting; // @synthesize userTargeting=_userTargeting;
- (void).cxx_destruct;
- (void)expire;
- (void)refreshTargetingData:(CDUnknownBlockType)arg1;
- (id)targetingParameter;
- (id)targetingString;
- (_Bool)dataHasExpired;
- (_Bool)idHasChanged;
- (void)saveTargetingData;
- (id)init;
- (id)initWithDictionary:(id)arg1;

@end

