//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Preferences/PSEditingPane.h>

#import <PreferencesUI/UITableViewDataSource-Protocol.h>
#import <PreferencesUI/UITableViewDelegate-Protocol.h>

@class NSString, PSTableCell, UIDatePicker, UITableView;

@interface DateRangePane : PSEditingPane <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_table;
    UIDatePicker *_datePicker;
    PSTableCell *_fromCell;
    PSTableCell *_toCell;
    struct __CFDateFormatter *_timeFormatter;
    int _selectedIndex;
}

@property(nonatomic) int selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(retain, nonatomic) UIDatePicker *datePicker; // @synthesize datePicker=_datePicker;
- (void).cxx_destruct;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)layoutSubviews;
- (void)update;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

