//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSNumber, PSSpecifier, PSUICarrierSpaceUsageCell;

@protocol PSUICarrierSpaceUsageCellDelegate

@optional
- (NSNumber *)otherUsage:(PSUICarrierSpaceUsageCell *)arg1 specifier:(PSSpecifier *)arg2;
- (NSNumber *)pairedWatchUsage:(PSUICarrierSpaceUsageCell *)arg1 specifier:(PSSpecifier *)arg2;
- (NSNumber *)thisDeviceUsage:(PSUICarrierSpaceUsageCell *)arg1 specifier:(PSSpecifier *)arg2;
- (NSNumber *)planCapacity:(PSUICarrierSpaceUsageCell *)arg1 specifier:(PSSpecifier *)arg2;
@end

