//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class VCVoIPRelayInternal;

@interface VCVoIPRelay : NSObject
{
    VCVoIPRelayInternal *_internal;
}

@property(readonly, nonatomic) unsigned long long blockSizeSamples;
@property(readonly, nonatomic) struct AudioStreamBasicDescription audioFormat;
- (void)stopWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)startWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithCaptureBlock:(CDUnknownBlockType)arg1 renderBlock:(CDUnknownBlockType)arg2;

@end

