//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ISCVirtualService;

__attribute__((visibility("hidden")))
@interface ISCVirtualServiceManager : NSObject
{
    ISCVirtualService *_mainDisplayButtonsService;
    ISCVirtualService *_mainDisplayTouchService;
    ISCVirtualService *_externalKeyboardService;
}

@property(retain, nonatomic) ISCVirtualService *externalKeyboardService; // @synthesize externalKeyboardService=_externalKeyboardService;
@property(retain, nonatomic) ISCVirtualService *mainDisplayTouchService; // @synthesize mainDisplayTouchService=_mainDisplayTouchService;
@property(retain, nonatomic) ISCVirtualService *mainDisplayButtonsService; // @synthesize mainDisplayButtonsService=_mainDisplayButtonsService;
- (void).cxx_destruct;
- (id)serviceForIndigoHIDData:(CDStruct_bf74d165 *)arg1;
- (id)initWithEventSystem:(struct __IOHIDEventSystem *)arg1;

@end

