//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, PDFPage, PDFSelection;

__attribute__((visibility("hidden")))
@interface PDFPageSearchLayerPrivate : NSObject
{
    PDFPage *page;
    long long displayBox;
    PDFSelection *selection;
    NSMutableDictionary *selectionRects;
}

- (void).cxx_destruct;

@end

