//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface STTopUsageItemsView : UIView
{
    NSArray *_usageItems;
    NSArray *_viewItems;
}

@property(copy, nonatomic) NSArray *viewItems; // @synthesize viewItems=_viewItems;
- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *usageItems; // @synthesize usageItems=_usageItems;

@end

