//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSNumber, NSString;

@interface STUser : NSObject <NSCopying>
{
    _Bool _screenTimeEnabled;
    _Bool _remoteUser;
    _Bool _hasAllowances;
    _Bool _hasManagementSettings;
    unsigned long long _source;
    NSString *_name;
    NSNumber *_dsid;
    unsigned long long _type;
    NSString *_passcode;
}

+ (id)keyPathsForValuesAffectingHasPasscode;
+ (id)keyPathsForValuesAffectingCanStopSharingScreenTime;
+ (id)keyPathsForValuesAffectingCanStopScreenTime;
+ (id)keyPathsForValuesAffectingCanRemoveAllowances;
+ (id)keyPathsForValuesAffectingCanRemovePasscode;
+ (id)keyPathsForValuesAffectingCanTogglePasscode;
@property(nonatomic) _Bool hasManagementSettings; // @synthesize hasManagementSettings=_hasManagementSettings;
@property(copy, nonatomic) NSString *passcode; // @synthesize passcode=_passcode;
@property(nonatomic) _Bool hasAllowances; // @synthesize hasAllowances=_hasAllowances;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic, getter=isRemoteUser) _Bool remoteUser; // @synthesize remoteUser=_remoteUser;
@property(nonatomic, getter=isScreenTimeEnabled) _Bool screenTimeEnabled; // @synthesize screenTimeEnabled=_screenTimeEnabled;
@property(copy, nonatomic) NSNumber *dsid; // @synthesize dsid=_dsid;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool hasPasscode;
@property(readonly, nonatomic) _Bool forceParentalControls;
@property(readonly, nonatomic) _Bool canStopSharingScreenTime;
@property(readonly, nonatomic) _Bool canStopScreenTime;
@property(readonly, nonatomic) _Bool canRemoveAllowances;
@property(readonly, nonatomic) _Bool canRemovePasscode;
@property(readonly, nonatomic) _Bool canTogglePasscode;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithPersonalUser:(id)arg1 familyUser:(id)arg2;
- (id)init;

@end

