//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class MKAnnotationView;

__attribute__((visibility("hidden")))
@interface _MKAnnotationViewLayer : CALayer
{
    MKAnnotationView *_annotationView;
}

@property(nonatomic) __weak MKAnnotationView *annotationView; // @synthesize annotationView=_annotationView;
- (void).cxx_destruct;
- (void)renderInContext:(struct CGContext *)arg1;

@end

