//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NewsFeedLayout/NFLWidgetTileInfo.h>

@class NSString;

@interface NFLRecommendationWidgetTileInfo : NFLWidgetTileInfo
{
    _Bool _defaultForYou;
    NSString *_identifier;
    long long _widgetType;
}

@property(readonly, nonatomic) _Bool defaultForYou; // @synthesize defaultForYou=_defaultForYou;
@property(readonly, nonatomic) long long widgetType; // @synthesize widgetType=_widgetType;
- (id)identifier;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithIdentifier:(id)arg1 widgetType:(long long)arg2 defaultForYou:(_Bool)arg3;
- (id)initWithWidgetType:(long long)arg1 defaultForYou:(_Bool)arg2;
- (id)init;

@end

