//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebKit/NSObject-Protocol.h>

@class NSArray, NSObject, NSString, UIView;
@protocol NSSecureCoding, _WKFocusedElementInfo;

@protocol _WKFormInputSession <NSObject>
@property(nonatomic) _Bool forceSecureTextEntry;
@property(nonatomic) _Bool accessoryViewShouldNotShow;
@property(copy, nonatomic) NSArray *suggestions;
@property(retain, nonatomic) UIView *customInputView;
@property(copy, nonatomic) NSString *accessoryViewCustomButtonTitle;
@property(readonly, nonatomic) id <_WKFocusedElementInfo> focusedElementInfo;
@property(readonly, nonatomic) NSObject<NSSecureCoding> *userObject;
@property(readonly, nonatomic, getter=isValid) _Bool valid;
@end

