//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSProgress;

__attribute__((visibility("hidden")))
@interface _NSXPCConnectionRequestedReplyInfo : NSObject
{
    CDUnknownBlockType _cleanupBlock;
    NSProgress *_progress;
}

@property(retain) NSProgress *progress; // @synthesize progress=_progress;
@property(copy) CDUnknownBlockType cleanupBlock; // @synthesize cleanupBlock=_cleanupBlock;
- (void)dealloc;

@end

