//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <ContextKit/NSSecureCoding-Protocol.h>

@class NSArray, NSError, NSString;

@interface CKContextResponse : NSObject <NSSecureCoding>
{
    _Bool _discarded;
    _Bool _resultsNeedFiltering;
    NSString *_uuid;
    NSError *_error;
    NSArray *_results;
    NSString *_debug;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSString *debug; // @synthesize debug=_debug;
@property(nonatomic) _Bool resultsNeedFiltering; // @synthesize resultsNeedFiltering=_resultsNeedFiltering;
@property(retain, nonatomic) NSArray *results; // @synthesize results=_results;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;
- (void)discard;
- (id)resultByQuery:(id)arg1;
- (id)completer;
- (void)addDebug:(id)arg1;
- (void)appendToDebug:(id)arg1;
- (_Bool)isPlaceholder;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initPlaceholderWithUUID:(id)arg1;
- (id)initWithError:(id)arg1;
- (id)initWithResults:(id)arg1;

@end

