//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString, UIFont;

@interface CKPhoneNumberCompressor : NSObject
{
    NSString *_phoneNumber;
    UIFont *_font;
    double _desiredWidth;
    NSArray *_preferredCompressions;
}

@property(copy, nonatomic) NSArray *preferredCompressions; // @synthesize preferredCompressions=_preferredCompressions;
@property(nonatomic) double desiredWidth; // @synthesize desiredWidth=_desiredWidth;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
- (void).cxx_destruct;
- (id)_compressPhoneNumberIfFitsInCompressionLevel:(int)arg1;
- (id)compress;

@end

