//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImpactFeedbackGenerator.h>

@interface _UIFeedbackImpactBehavior : UIImpactFeedbackGenerator
{
}

+ (id)impactBehaviorWithCoordinateSpace:(id)arg1 configuration:(id)arg2;
+ (id)impactBehaviorWithStyle:(long long)arg1 coordinateSpace:(id)arg2;
- (void)impactOccurredWithIntensity:(double)arg1;

@end

