//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <UIKit/UIViewControllerTransitioningDelegate-Protocol.h>

@class NSString, UIPreviewInteraction;
@protocol UIPreviewInteractionAnimating><UIViewControllerAnimatedTransitioning><UIViewControllerInteractiveTransitioning;

__attribute__((visibility("hidden")))
@interface _UIPreviewInteractionViewControllerTransition : NSObject <UIViewControllerTransitioningDelegate>
{
    UIPreviewInteraction *_previewInteraction;
    id <UIPreviewInteractionAnimating><UIViewControllerAnimatedTransitioning><UIViewControllerInteractiveTransitioning> _previewInteractionAnimator;
}

@property(retain, nonatomic) id <UIPreviewInteractionAnimating><UIViewControllerAnimatedTransitioning><UIViewControllerInteractiveTransitioning> previewInteractionAnimator; // @synthesize previewInteractionAnimator=_previewInteractionAnimator;
@property(retain, nonatomic) UIPreviewInteraction *previewInteraction; // @synthesize previewInteraction=_previewInteraction;
- (void).cxx_destruct;
- (id)_preparedPreviewInteractionAnimator;
- (id)presentationControllerForPresentedViewController:(id)arg1 presentingViewController:(id)arg2 sourceViewController:(id)arg3;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)initWithPreviewInteraction:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

