//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SearchFoundation/SFText.h>

#import <SearchFoundation/NSSecureCoding-Protocol.h>

@class SFImage;

@interface SFFormattedText : SFText <NSSecureCoding>
{
    _Bool _isEmphasized;
    _Bool _isBold;
    SFImage *_glyph;
    unsigned long long _textColor;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) unsigned long long textColor; // @synthesize textColor=_textColor;
@property(nonatomic) _Bool isBold; // @synthesize isBold=_isBold;
@property(nonatomic) _Bool isEmphasized; // @synthesize isEmphasized=_isEmphasized;
@property(retain, nonatomic) SFImage *glyph; // @synthesize glyph=_glyph;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

