//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NanoTimeKitCompanion/NTKCFaceDetailSectionController.h>

@class NTKCFaceDetailSyncedAlbumCell;

@interface NTKCFaceDetailSyncedAlbumSectionController : NTKCFaceDetailSectionController
{
}

+ (_Bool)hasSyncedAlbumSectionForFace:(id)arg1 inGallery:(_Bool)arg2;
- (void)faceDidChange;
- (void)_commonInit;

// Remaining properties
@property(retain, nonatomic) NTKCFaceDetailSyncedAlbumCell *cell; // @dynamic cell;

@end

