//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NanoTimeKitCompanion/NTKCompanionResourceDirectoryEditor.h>

@class NSMutableArray, NSMutableDictionary;

@interface NTKCompanionCustomPhotosEditor : NTKCompanionResourceDirectoryEditor
{
    NSMutableDictionary *_pickedPhotos;
    NSMutableDictionary *_newPhotos;
    NSMutableArray *_orderList;
    _Bool _previewIsValid;
}

- (void).cxx_destruct;
- (void)_reinitializeWithImageList:(id)arg1 andResourceDirectory:(id)arg2;
- (id)_copyOrTranscodePhotosTo:(id)arg1;
- (id)_fetchAssetsForNewPhotos:(id)arg1;
- (void)_fetchAssetsForPickedPhotos;
- (void)_readPickedPhotosFrom:(id)arg1;
- (struct CGRect)originalCropForPhotoAtIndex:(long long)arg1;
- (id)imageInPhotoLibraryForPhotoAtIndex:(long long)arg1;
- (id)imageForPhotoAtIndex:(long long)arg1;
- (_Bool)isPhotoInPhotoLibraryAtIndex:(long long)arg1;
- (void)setOriginalCrop:(struct CGRect)arg1 forPhotoAtIndex:(long long)arg2;
- (void)movePhotoAtIndex:(long long)arg1 toIndex:(long long)arg2;
- (void)deletePhotoAtIndex:(long long)arg1;
- (_Bool)addAssetsFromAssetList:(id)arg1;
- (_Bool)addPhotosFromUIImagePicker:(id)arg1;
@property(readonly, nonatomic) long long photosCount;
- (void)finalizeWithCompletion:(CDUnknownBlockType)arg1;
- (void)generateGalleryPreviewResourceDirectoryWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithResourceDirectory:(id)arg1;

@end

