//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPTemplateDelegate.h"

@class CPNavigationAlert, NSUUID;

@protocol CPMapClientTemplateDelegate <CPTemplateDelegate>
- (void)clientTripCanceledByExternalNavigation;
- (void)clientNavigationAlertDidDisappear:(CPNavigationAlert *)arg1 context:(unsigned long long)arg2;
- (void)clientNavigationAlertWillDisappear:(CPNavigationAlert *)arg1 context:(unsigned long long)arg2;
- (void)clientNavigationAlertDidAppear:(CPNavigationAlert *)arg1;
- (void)clientNavigationAlertWillAppear:(CPNavigationAlert *)arg1;
- (void)clientPanViewWillDisappear;
- (void)clientPanViewDidDisappear;
- (void)clientPanViewDidAppear;
- (void)clientPanWithDirection:(unsigned long long)arg1;
- (void)clientPanEndedWithDirection:(unsigned long long)arg1;
- (void)clientPanBeganWithDirection:(unsigned long long)arg1;
- (void)startTripIdentifier:(NSUUID *)arg1 usingRouteIdentifier:(NSUUID *)arg2;
- (void)previewTripIdentifier:(NSUUID *)arg1 usingRouteIdentifier:(NSUUID *)arg2;
@end

