//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSError;

@interface CNObservableEvent : NSObject
{
}

+ (id)failureEventWithError:(id)arg1;
+ (id)completionEvent;
+ (id)eventWithResult:(id)arg1;
- (void)dematerializeWithObserver:(id)arg1;
@property(readonly, copy, nonatomic) NSError *error;
@property(readonly, nonatomic) id value;
@property(readonly, nonatomic) _Bool hasValue;
@property(readonly, nonatomic) unsigned long long eventType;

@end

