//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CNPhoneNumberScanner : NSObject
{
}

- (void)withPhoneNumbersInString:(id)arg1 each:(CDUnknownBlockType)arg2;
- (void)enumeratePhoneNumbersInString:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)firstPhoneNumberInString:(id)arg1;

@end

