//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSIndexSet.h>

@interface NSIndexSet (ContactsFoundation)
- (id)_cn_map:(CDUnknownBlockType)arg1;
- (_Bool)_cn_any:(CDUnknownBlockType)arg1;
- (_Bool)_cn_all:(CDUnknownBlockType)arg1;
@end

