//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class SKPaymentQueueClient, SKXPCConnection;
@protocol SKRequestDelegate;

@interface SKRequestInternal : NSObject
{
    long long _backgroundTaskIdentifier;
    SKPaymentQueueClient *_client;
    SKXPCConnection *_connection;
    id <SKRequestDelegate> _delegate;
    long long _state;
}

- (void)dealloc;

@end

