//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FitnessUI/FUChartSeries.h>

@class NSArray, NSDate;

@interface FUUniformBarSeries : FUChartSeries
{
    NSDate *_minDate;
    double _barWidth;
    double _barSpacing;
    double _roundedCornerRadius;
    double _fadeInPercentage;
    struct CGGradient *_barGradient;
    NSArray *_plotPoints;
}

@property(retain, nonatomic) NSArray *plotPoints; // @synthesize plotPoints=_plotPoints;
@property(nonatomic) struct CGGradient *barGradient; // @synthesize barGradient=_barGradient;
@property(nonatomic) double fadeInPercentage; // @synthesize fadeInPercentage=_fadeInPercentage;
@property(nonatomic) double roundedCornerRadius; // @synthesize roundedCornerRadius=_roundedCornerRadius;
@property(nonatomic) double barSpacing; // @synthesize barSpacing=_barSpacing;
@property(nonatomic) double barWidth; // @synthesize barWidth=_barWidth;
@property(nonatomic) NSDate *minDate; // @synthesize minDate=_minDate;
- (void).cxx_destruct;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (double)_getYValueForPointFromChartPoint:(id)arg1;
- (double)_getXValueForPointFromChartPoint:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

