//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

__attribute__((visibility("hidden")))
@interface PUPhotoStreamAlbumTableViewCell : UITableViewCell
{
}

+ (double)labelXOriginForContentWidth:(double)arg1 labelWidth:(double)arg2 isRTL:(_Bool)arg3;
+ (double)labelHorizontalInset;
+ (double)cellHeight;
- (void)layoutSubviews;

@end

