//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PXGadgetDataSourceManager.h"

#import "PXSettingsKeyObserver.h"

@class NSString, PUSearchZeroKeywordGadgetProvider, PXNoContentGadget;

__attribute__((visibility("hidden")))
@interface PUSearchHomeGadgetDataSourceManager : PXGadgetDataSourceManager <PXSettingsKeyObserver>
{
    PUSearchZeroKeywordGadgetProvider *_zeroKeywordGadgetProvider;
    PXNoContentGadget *_searchNoContentGadget;
}

@property(retain, nonatomic) PXNoContentGadget *searchNoContentGadget; // @synthesize searchNoContentGadget=_searchNoContentGadget;
@property(retain, nonatomic) PUSearchZeroKeywordGadgetProvider *zeroKeywordGadgetProvider; // @synthesize zeroKeywordGadgetProvider=_zeroKeywordGadgetProvider;
- (void).cxx_destruct;
- (void)ppt_prepareZeroKeywordRequest:(CDUnknownBlockType)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (id)_sortingRankForGadget:(id)arg1;
- (void)refreshData;
- (id)filteredUndisplayedGadgets:(id)arg1;
- (CDUnknownBlockType)gadgetSortComparator;
- (id)noContentGadget;
- (id)gadgetProviders;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

