//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (MTUtilities)
+ (CDUnknownBlockType)mtCurrentDateProvider;
- (id)mtDateNearestMatchingComponents:(id)arg1;
- (_Bool)mtIsAfterOrSameDate:(id)arg1;
- (_Bool)mtIsAfterDate:(id)arg1;
- (_Bool)mtIsBeforeOrSameAsDate:(id)arg1;
- (_Bool)mtIsBeforeDate:(id)arg1;
@end

