//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CameraUI/NSCoding-Protocol.h>

@interface CAMCaptureGraphConfiguration : NSObject <NSCoding>
{
    long long _mode;
    long long _device;
    long long _videoConfiguration;
    long long _audioConfiguration;
    long long _previewConfiguration;
}

@property(readonly, nonatomic) long long previewConfiguration; // @synthesize previewConfiguration=_previewConfiguration;
@property(readonly, nonatomic) long long audioConfiguration; // @synthesize audioConfiguration=_audioConfiguration;
@property(readonly, nonatomic) long long videoConfiguration; // @synthesize videoConfiguration=_videoConfiguration;
@property(readonly, nonatomic) long long device; // @synthesize device=_device;
@property(readonly, nonatomic) long long mode; // @synthesize mode=_mode;
- (id)description;
- (id)completeDescription;
- (id)shortDescription;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithCaptureMode:(long long)arg1 captureDevice:(long long)arg2 videoConfiguration:(long long)arg3 audioConfiguration:(long long)arg4 previewConfiguration:(long long)arg5;

@end

