//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FrontBoard/NSObject-Protocol.h>

@class FBProcess, NSObject;
@protocol FBSystemServiceFacilityClient, OS_xpc_object;

@protocol FBSystemServiceClient <NSObject>
@property(retain, nonatomic) id <FBSystemServiceFacilityClient> facilityClient;
@property(readonly, retain, nonatomic) NSObject<OS_xpc_object> *connection;
@property(readonly, retain, nonatomic) FBProcess *process;
@property(readonly, nonatomic, getter=isSuspended) _Bool suspended;
@property(readonly, nonatomic) int pid;
@end

