//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreHandwriting/CHStrokeGroupingStrategy.h>

@interface CHBottomUpStrokeGroupingStrategy : CHStrokeGroupingStrategy
{
}

+ (double)_vectorMeanWithoutOutliers:(vector_8f06c10f *)arg1;
+ (double)_circumferenceRatioOfCircleFittedToPoints:(list_9bacdeb6)arg1 circleCenter:(struct CGPoint *)arg2 circleRadius:(double *)arg3;
+ (vector_fa824bf3)_convexHullForPoints:(vector_fa824bf3 *)arg1;
+ (vector_fa824bf3)_convexHullForStroke:(id)arg1;
- (struct CGRect)_unionStrokeBounds:(const vector_ea45b3ba *)arg1 usingStrokeCountLimit:(long long)arg2 reverseOrder:(_Bool)arg3;
- (vector_ea45b3ba)_boundingBoxesOfStrokesInGroup:(id)arg1 rotatedAroundPoint:(struct CGPoint)arg2 byAngle:(double)arg3;
- (id)averageAngleAndReliabilityForStrokeGroup:(id)arg1;
- (void)_mergeGroupsPostProcessing:(id)arg1 createdGroups:(id)arg2 deletedGroups:(id)arg3;
- (void)_updateLocalStrokeDeviationsForSubstrokes:(id)arg1 averageStrokeDeviation:(struct CGVector *)arg2;
- (_Bool)_refineWritingOrientationAndResortSubstrokes:(id)arg1;
- (vector_fa824bf3)_flippedCenters:(const vector_fa824bf3 *)arg1 ofSubstrokes:(id)arg2 maxStrokesGap:(long long)arg3 begnning:(_Bool)arg4;
- (void)_refineLocalWritingOrientationsForSubstrokes:(id)arg1 useCoalescedCenter:(_Bool)arg2;
- (void)_smoothLocalWritingOrientations:(vector_892a0aec *)arg1;
- (void)_updateLocalWritingOrientationsForSubstrokes:(id)arg1 useCoalescedCenter:(_Bool)arg2;
- (void)_sortSubstrokesByWritingDirection:(id)arg1 averageWritingOrientation:(struct CGVector *)arg2;
- (void)_estimateWritingDirectionAndSortSubstrokesAccordingly:(id)arg1 averageWritingOrientation:(struct CGVector *)arg2 averageStrokeDeviation:(struct CGVector *)arg3;
- (id)_substrokesForStroke:(id)arg1;
- (struct CGVector)_averageVectorFromSubstroke:(id)arg1 toSubstroke:(id)arg2 withOrientation:(struct CGVector)arg3 strokeRef:(id)arg4;
- (long long)_compareDistanceInWritingSequenceOfStroke:(id)arg1 andStroke:(id)arg2 toReferenceStroke:(id)arg3;
- (void)_getMergingMiddleOfLineCost:(double *)arg1 mergingMiddleOfLineStroke:(id *)arg2 forStrokeSubstrokes:(id)arg3 toLineGroup:(id)arg4;
- (void)_getMergingEndOfLineCost:(double *)arg1 mergingEndOfLineStroke:(id *)arg2 forStrokeSubstrokes:(id)arg3 toLineGroup:(id)arg4;
- (id)_writingDirectionSortedStrokeIdentifiersFromSubstrokes:(id)arg1 localWritingOrientations:(vector_892a0aec *)arg2;
- (double)_verticalOffsetForBoundsHeight:(double)arg1 andScaleFactor:(double)arg2;
- (double)_scaleFactorForBoundsHeight:(double)arg1;
- (id)recognizableDrawingForStrokeGroup:(id)arg1 orderedStrokesIDs:(id *)arg2;
- (void)_updateGroups:(id)arg1 createdGroups:(id)arg2 deletedGroups:(id)arg3 forAddedStroke:(id)arg4;
- (id)updatedGroupingResult;
- (id)initWithStrokeProvider:(id)arg1 sessionLastResult:(id)arg2 locales:(id)arg3;

@end

