//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValue.h"

@interface NSValue (OFNSValueExtension)
+ (id)valueWithMKCoordinateRegion:(CDStruct_2b0c6e0b)arg1;
+ (id)valueWithCLLocationCoordinate2D:(struct CLLocationCoordinate2D)arg1;
- (CDStruct_2b0c6e0b)MKCoordinateRegionValue;
- (struct CLLocationCoordinate2D)CLLocationCoordinate2DValue;
@end

