//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IMAPAccount, NSArray;

@interface _MFIMAPMailboxDeletionQueueEntry : NSObject
{
    NSArray *urls;
    NSArray *paths;
    IMAPAccount *account;
}

@property(retain) IMAPAccount *account; // @synthesize account;
@property(copy) NSArray *paths; // @synthesize paths;
@property(copy) NSArray *urls; // @synthesize urls;
- (void)dealloc;

@end

