//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GeoServices/GEOAbstractMapServiceTicket.h>

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface _GEOIdentifiersTicket : GEOAbstractMapServiceTicket
{
    NSArray *_identifiers;
    int _resultProviderID;
    NSString *_contentProvider;
    _Bool _includeETA;
    unsigned long long _options;
}

- (void).cxx_destruct;
- (void)submitWithHandler:(CDUnknownBlockType)arg1 timeout:(long long)arg2 networkActivity:(CDUnknownBlockType)arg3;
- (id)description;
- (id)initWithIdentifiers:(id)arg1 resultProviderID:(int)arg2 contentProvider:(id)arg3 includeETA:(_Bool)arg4 traits:(id)arg5 options:(unsigned long long)arg6;
- (id)initWithMUIDs:(id)arg1 resultProviderID:(int)arg2 contentProvider:(id)arg3 includeETA:(_Bool)arg4 traits:(id)arg5 options:(unsigned long long)arg6;

@end

