//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GeoServices/NSObject-Protocol.h>

@class GEOPDVenueIdentifier, NSArray;
@protocol GEOVenueComponentIdentifier;

@protocol GEOVenueIdentifier <NSObject>
@property(readonly, nonatomic) NSArray *componentIdentifiers;
@property(readonly, nonatomic) unsigned long long businessID;
@property(readonly, nonatomic, getter=_hasBusinessID) _Bool hasBusinessID;
@property(readonly, nonatomic) unsigned long long venueID;
@property(readonly, nonatomic, getter=_hasVenueID) _Bool hasVenueID;
- (GEOPDVenueIdentifier *)placeDataVenueIdentifierForBuilding:(id <GEOVenueComponentIdentifier>)arg1;
- (GEOPDVenueIdentifier *)placeDataVenueIdentifierForVenue;
@end

