//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TelephonyUtilities/TUAudioController.h>

@class NSArray, NSNumber, NSObject;
@protocol OS_dispatch_queue;

@interface TUAudioSystemController : TUAudioController
{
    NSObject<OS_dispatch_queue> *_uplinkMutedQueue;
    NSObject<OS_dispatch_queue> *_downlinkMutedQueue;
    NSObject<OS_dispatch_queue> *_ttyQueue;
    NSObject<OS_dispatch_queue> *_pickableRoutesQueue;
    NSNumber *_isUplinkMutedCached;
    NSNumber *_isDownlinkMutedCached;
    NSNumber *_isTTYCached;
    NSArray *_pickableRoutesForTTY;
    NSArray *_pickableRoutesForPhoneCall;
    NSArray *_pickableRoutesForPlayAndRecordVideo;
    NSArray *_pickableRoutesForPlayAndRecordVoice;
    NSArray *_pickableRoutesForPlayAndRecordRemoteVoice;
    NSArray *_pickableRoutesForVoicemail;
    NSArray *_currentPickableRoutes;
    _Bool _isRequestingUplinkMuted;
    _Bool _isRequestingDownlinkMuted;
    _Bool _isRequestingTTY;
    _Bool _isRequestingPickableRoutesForTTY;
    _Bool _isRequestingPickableRoutesForPhoneCall;
    _Bool _isRequestingPickableRoutesForPlayAndRecordVideo;
    _Bool _isRequestingPickableRoutesForPlayAndRecordVoice;
    _Bool _isRequestingPickableRoutesForPlayAndRecordRemoteVoice;
    _Bool _isRequestingPickableRoutesForVoicemail;
    unsigned long long _lastUplinkMutedRequestScheduleTime;
    unsigned long long _lastDownlinkMutedRequestScheduleTime;
    unsigned long long _lastTTYRequestScheduleTime;
    unsigned long long _lastTTYPickableRoutesScheduleTime;
    unsigned long long _lastPhoneCallCategoryRoutesScheduleTime;
    unsigned long long _lastPlayAndRecordVideoRoutesScheduleTime;
    unsigned long long _lastPlayAndRecordVoiceRoutesScheduleTime;
    unsigned long long _lastPlayAndRecordRemoteVoiceRoutesScheduleTime;
    unsigned long long _lastVoicemailRoutesScheduleTime;
}

+ (id)sourceIdentifierForRouteID:(id)arg1;
+ (id)sharedAudioSystemController;
+ (id)sharedSystemController;
- (void).cxx_destruct;
- (_Bool)shouldSuppressCallUsingRoute:(id)arg1;
- (id)pickableRouteWithUniqueIdentifier:(id)arg1;
- (void)_getPickableRoutesForCategory:(id)arg1 mode:(id)arg2 onlyKnownCombinations:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)getPickableRoutesForCategory:(id)arg1 mode:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)pickableRoutesForCategory:(id)arg1 andMode:(id)arg2;
- (id)bestGuessPickableRoutesForAnyCall;
- (void)_loadCurrentPickableRoutesWithCompletion:(CDUnknownBlockType)arg1;
- (id)_pickableRoutesForVoiceMailWithForceNewRequest:(_Bool)arg1;
- (id)_pickableRoutesForPlayAndRecordRemoteVoiceWithForceNewRequest:(_Bool)arg1;
- (id)_pickableRoutesForPlayAndRecordVideoWithForceNewRequest:(_Bool)arg1;
- (id)_pickableRoutesForPlayAndRecordVoiceWithForceNewRequest:(_Bool)arg1;
- (id)currentlyPickedRouteIdForCategory:(id)arg1 andMode:(id)arg2;
- (id)_pickableRoutesForPhoneCallWithForceNewRequest:(_Bool)arg1;
- (id)pickableRoutesForTTY;
- (id)_pickableRoutesForTTYWithForceNewRequest:(_Bool)arg1;
@property(nonatomic, getter=isDownlinkMuted) _Bool downlinkMuted;
@property(nonatomic, getter=isUplinkMuted) _Bool uplinkMuted;
@property(readonly, nonatomic, getter=isTTY) _Bool tty;
- (void)_handleServerConnectionDiedNotification:(id)arg1;
- (void)_handlePickableRoutesDidChangeNotification:(id)arg1;
- (void)_handleDownlinkMuteDidChangeNotification:(id)arg1;
- (void)_handleUplinkMuteDidChangeNotification:(id)arg1;
- (void)_updateCachedState;
- (void)dealloc;
- (id)init;

@end

