//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBSCyclerOperation : NSObject
{
    unsigned long long _numberOfRemainingAttempts;
    _Bool _finished;
    _Bool _executing;
    CDUnknownBlockType _block;
}

@property(readonly, nonatomic, getter=isExecuting) _Bool executing; // @synthesize executing=_executing;
@property(readonly, nonatomic, getter=isFinished) _Bool finished; // @synthesize finished=_finished;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (void)executeWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithMaximumNumberOfAttempts:(unsigned long long)arg1;
- (id)init;

@end

