//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SafariShared/WBSParsecSearchResult.h>

#import <SafariShared/WBSParsecSearchMapsResultFeedbackSenderClient-Protocol.h>
#import <SafariShared/WBSParsecSearchResultPresentedInCard-Protocol.h>

@class NSString, NSURL, WBSParsecSearchMapsResultExtraCompletionItem, WBSParsecSearchMapsResultFeedbackSender;
@protocol WBSParsecSearchSession;

@interface WBSParsecSearchMapsResult : WBSParsecSearchResult <WBSParsecSearchMapsResultFeedbackSenderClient, WBSParsecSearchResultPresentedInCard>
{
    NSString *_mapsDataType;
    WBSParsecSearchMapsResultFeedbackSender *_mapsFeedbackSender;
    NSString *_mapsResultType;
    NSURL *_moreURL;
    NSString *_nearbyBusinessesString;
    WBSParsecSearchMapsResultExtraCompletionItem *_extraCompletionItem;
    id <WBSParsecSearchSession> _parsecSearchSession;
    WBSParsecSearchResult *_hiddenParsecResult;
}

@property(retain, nonatomic) WBSParsecSearchResult *hiddenParsecResult; // @synthesize hiddenParsecResult=_hiddenParsecResult;
@property(retain, nonatomic) id <WBSParsecSearchSession> parsecSearchSession; // @synthesize parsecSearchSession=_parsecSearchSession;
@property(readonly, nonatomic) WBSParsecSearchMapsResultExtraCompletionItem *extraCompletionItem; // @synthesize extraCompletionItem=_extraCompletionItem;
@property(readonly, nonatomic) NSString *nearbyBusinessesString; // @synthesize nearbyBusinessesString=_nearbyBusinessesString;
@property(readonly, nonatomic) NSURL *moreURL; // @synthesize moreURL=_moreURL;
@property(readonly, nonatomic) NSString *mapsResultType; // @synthesize mapsResultType=_mapsResultType;
@property(retain, nonatomic) WBSParsecSearchMapsResultFeedbackSender *mapsFeedbackSender; // @synthesize mapsFeedbackSender=_mapsFeedbackSender;
- (void).cxx_destruct;
- (void)didDisplayMapsResultForQuery:(id)arg1;
@property(readonly, nonatomic) _Bool willPresentResultInCard;
- (id)supportedStyleOverrides;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

