//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPSExternalPluginBase.h"

@interface MPSExternalCNNBinary : MPSExternalPluginBase
{
}

- (unsigned long long)encodeWithFilter:(id)arg1 encoder:(id)arg2 commandBuffer:(id)arg3 callInfo:(const CDStruct_7282e41a *)arg4;
- (unsigned long long)encodeToCommandBuffer:(id)arg1 computeCommandEncoder:(id)arg2 options:(unsigned long long)arg3 primaryTexture:(id)arg4 primaryInfo:(const CDStruct_15cf940b *)arg5 secondaryTexture:(id)arg6 secondaryInfo:(const CDStruct_15cf940b *)arg7 destinationTexture:(id)arg8 destinationInfo:(const CDStruct_3d604284 *)arg9;

@end

