//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol PLCloudChangeTrackerDelegate <NSObject>
- (void)saveTokenObject:(id)arg1 forKey:(NSString *)arg2;
- (id)readTokenObjectWithKey:(NSString *)arg1;
- (void)changeTrackerDidReceiveChanges;
@end

