//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryServices/PSITable.h>

@class PSIStatement;

@interface PSITripTable : PSITable
{
    PSIStatement *_insertStatement;
    PSIStatement *_deleteStatement;
    PSIStatement *_checkStatement;
    PSIStatement *_listStatement;
    PSIStatement *_tripResultsForTripIdsStatement;
    PSIStatement *_selectWithSingleDateStatement;
    PSIStatement *_selectWithStartEndDatesStatement;
    PSIStatement *_selectWithStartDateStatement;
    PSIStatement *_selectWithEndDateStatement;
    PSIStatement *_selectByGroupIdWithSingleDateStatement;
    PSIStatement *_selectByGroupIdWithStartEndDatesStatement;
    PSIStatement *_selectByGroupIdWithStartDateStatement;
    PSIStatement *_selectByGroupIdWithEndDateStatement;
    PSIStatement *_selectByGroupIdStatement;
    PSIStatement *_groupIdsWithTripIdsStatement;
    PSIStatement *_linkToMomentStatement;
    PSIStatement *_unlinkFromAllMomentsStatement;
    PSIStatement *_getMomentsStatement;
    PSIStatement *_linkToGroupStatement;
    PSIStatement *_unlinkFromGroupsStatement;
    PSIStatement *_checkGroupStatement;
}

- (void).cxx_destruct;
- (id)removeAllTrips;
- (void)removeTripForId:(long long)arg1;
- (const struct __CFSet *)unlinkTripForId:(long long)arg1;
- (id)allTripUUIDs;
- (long long)tripIdForUUID:(id)arg1;
- (const struct __CFSet *)newGroupIdsWithTripIds:(struct __CFSet *)arg1;
- (const struct __CFArray *)newTripIdsWithDateFilter:(id)arg1;
- (const struct __CFArray *)newTripIdsWithGroupId:(long long)arg1 dateFilter:(id)arg2;
- (id)tripResultsForTripIds:(struct __CFArray *)arg1 range:(struct _NSRange)arg2;
- (long long)addTrip:(id)arg1 usingTokenEnumeratingBlock:(CDUnknownBlockType)arg2;
- (void)cacheOtherStatements;
- (void)cacheSearchableStatements;
- (void)cacheWritableStatements;
- (void)clear;
- (void)finalizze;
- (id)initWithDelegate:(id)arg1 searchable:(_Bool)arg2 writable:(_Bool)arg3;

@end

