//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMapTable, NSMutableDictionary;

@interface TIKeyboardInputManagerLoaderSyncHelper : NSObject
{
    NSMutableDictionary *_languages;
    NSMapTable *_pendingSaves;
    CDUnknownBlockType _languageUpdated;
}

@property(copy, nonatomic) CDUnknownBlockType languageUpdated; // @synthesize languageUpdated=_languageUpdated;
- (_Bool)shouldCacheObject:(id)arg1;
- (void)noteObject:(id)arg1 forLanguage:(id)arg2;
- (void)willLoadLanguage:(id)arg1;
- (void)languagePulled:(id)arg1;
- (void)languagesChanged:(id)arg1;
- (void)dealloc;
- (id)init;

@end

