//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MTLSpline/MTLSPath.h>

@class NSMutableArray;

@interface MTLSPathUnion : MTLSPath
{
    NSMutableArray *_paths;
}

- (void).cxx_destruct;
- (id)initWithPaths:(id)arg1;

@end

