//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  7 2017 08:40:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, PDFDocument, PDFDocumentContentView, PDFRenderingProperties, PDFView, PageImagePool;

__attribute__((visibility("hidden")))
@interface PDFDocumentViewPrivate : NSObject
{
    PDFView *pdfView;
    PDFDocument *document;
    PDFRenderingProperties *renderingProperties;
    struct CGSize documentViewSize;
    PDFDocumentContentView *contentView;
    NSMutableDictionary *pageViews;
    NSMutableDictionary *pageFrames;
    PageImagePool *pageImagePool;
    _Bool ignoreChangedBoundsForBoxNotification;
    _Bool showTextSelectionHandles;
}

- (void).cxx_destruct;

@end

